### ISSUE TITLE
Buildmap function broken by switch to SDL2

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#102]
With the switch to SDL2 each of the superchunks that Exult screenshots have an extra black border of 4 pixels. So instead of 2048x2048 pixels, each pcx file is 2056x2056.

Since these screenshots are made using the point scaler at 1x buildmap was actually completely broken until fc6962d413.

**Comment by DominusExult** [comment]
The Screenshot function has the same problem (though for that a black border is not fatal).

The problem seems to be that in imagewin/savepcx.cc SDL_Surface gives the wrong dimensions (adding a 4pixel border around the actual size):
```
static bool save_image(SDL_Surface *surface, SDL_RWops *dst) {
	Uint8 *cmap = nullptr;
	int colors = 0;
	int width = surface->w;
	int height = surface->h;
```

**Comment by DominusExult** [comment]
if I change this part to
```
static bool save_image(SDL_Surface *surface, SDL_RWops *dst) {
	Uint8 *cmap = nullptr;
	int colors = 0;
	int width = surface->w - 8;
	int height = surface->h - 8;
	auto *pixels = static_cast<Uint8 *>(surface->pixels)+4;
```
the screenshot has 
- the right dimension 
- there is no border to the left and right (the visible game screen shifted 4 pixels to the left)
- no border on the bottom
- 4 pixel border on top
- the visible game screen is cut off by 4 pixels at the bottom since it's not shifted up by 4 pixels

@wench sorry to bother you but maybe you have an idea?

328x208 border all around (changed black border to green for better visibility)
![exult000](https://user-images.githubusercontent.com/3313896/152254465-d862687e-ea90-48b9-8cd1-286f971e6ad9.png)

after change, 320x200 border only on top, bottom cut off
![exult053](https://user-images.githubusercontent.com/3313896/152254467-2288ea82-c75a-49f5-9bd7-ea9b99ab4bf9.png)

**Comment by wench** [comment]
@DominusExult I have no real idea about that feature or SDL2 but this will probably help get rid of the top border. just offset down by 4 lines
auto *pixels = static_cast<Uint8 *>(surface->pixels)+4+surface->pitch*4;

**Comment by wench** [comment]
I say i have no real idea but its not actually true. Exult puts a guardband around the rendered image for protection against scalers that don't properly bound check and can read off the edge of the screen. The save_image function really should only apply the fix for the guardband if its actually inuse by imagewin

**Comment by wench** [comment]
Assigning this to myself as i have a pretty good idea about what's going on after thinking about it.

**Comment by DominusExult** [comment]
Thank you very much @wench. I've been using the buildmap lately a lot for a project and so far had to use the SDL 1.2 release of Exult 1.6 for this which was a pain :)

**Comment by wench** [comment]
No problem. Your recent comment to this issue by chance was just after i had looked at related code so i could work out what was going on. A simple problem really so I could do a quick fix. 
I am a little surprised things worked in SDL 1.2, there must have been big code changes when moving to SDL 2.0 and the screenshot code must have worked a bit differently and probably didn't use a SDL_Surface. I could check the change history, but it doesn't really matter.
I do wonder if we should have a option to output scaled screenshots instead of the 8 bit unscaled pcx screenshots we do now. What you get as a screenshot doesn't really match what you see on screen.

**Comment by DominusExult** [comment]
There was a lot of stuff breaking and I think some is still a tiny bit broken (1x scalers other than point do not work but use point, e.g. interlace) but mostly stuff that no one uses :)
Meanwhile your fix stirred up @Dragon-Baroque's interest in changing the screenshots to png.
Pros:
- pcx is not an image format every viewer knows how to handle these days. It's so uncommon that they forgot all about it. EVERY viewer can display png
- the file size of png is potentially a third of pcx

cons:
- the pcx code is very lightweight
- > we would add another dependency (libpng) but it's an easy dependency and when we enable Exult Studio support we are already depending on it.

While discussing it I mentioned the same weirdness of small screenshots that don't match the visible screen (and can't be taken when an Exult menu gump is up. So yes, it might be useful to have scaling there :)
OTOH people probably don't use the builtin screenshot function other than the buildmap one (and apparently it's not been used by someone else but me recently).

**Comment by wench** [comment]
The screenshot function is not part of Exults keybinding system and doesn't appear in the ingame help so people probably don't know it exists. 
I think png is a good idea. If people don't have the libpng dependency when building Exult screenshots should just be disabled

**Comment by Dragon-Baroque** [comment]
With this issue being closed, I am not sure whether it is the right channel.

Anyway, I have just posted a new branch `exult_png_snapshot` on `Dragon-Baroque/exult` to prototype the move to PNG for Exult Screenshots and Buildmaps.

It is probably not pull request ready, at least because I do not know how to update the build chains for Windows or iOS, but if you can take a look into it :

Depending on whether `configure` finds `png.h`, positioning `#ifdef` variable `HAVE_PNG_H` and Makefile variable `HAVE_PNG` :
- `Makefile.am` adds `-lpng` to exult,
- `exult.cc` alters the image suffix `pcx` to `png`,
- `imagewin/savepcx.cc` uses a `libpng` API to produce a PNG image.

Since Screenshots and Buildmaps end up into the same code path in `imagewin/savepcx.cc`, this code change works for both.

**Comment by DominusExult** [comment]
yeah, we probably need a new topic for this:
That said, don't worry about iOS at least. Even though I am able to add the libpng dependency it is not needed for iOS at all. Neither screenshot or buildmap has any function on iOS (I could have recognized that before, yes). Screenshots are done by the usual way you do it on a smartphone these days (in case of iOS by pressing some buttons), I've not added a way to Exult on iOS to use the build in function. And buildmap is a command line option and that's not supported at all.
So as long as the png support is optional, it is not needed on that platform.
Great work, thank you!

**Comment by Dragon-Baroque** [comment]
Well, you gave me the pointer to the exact code that was needed, which I took and simplified a bit.

I have pushed a replacement for the branch :
- Update to `Makefile.mingw` to add `libpng` to Exult, since in it, `HAVE_PNG_H` is unconditionnally set.
That should handle the Windows build, too, but I have not tested it, nor have I tested it on macOS.
