### ISSUE TITLE
Exult only shows "useful window resolutions" not all available modes

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#105]
fad56cf6 broke showing available modes and now only shows the "useful window resolutions".

**Comment by Dreded** [comment]
if it helps.. the workaround right now is to set it full screen, adjust to desired resolution then window it.

**Comment by Dreded** [comment]
Question, what's the use case for setting "Window Size" at all if "Game Area" = 320x200? why would I ever want my window not to be a 320x200 * scale?

**Comment by DominusExult** [comment]
I don't think people have an initial setup issue. 
Window size is meant to determine how big your Exult window should be. And as people like to play in higher game area sizes you don't always have multiples of 320x200.
One big use case is of course editing the game via Exult Studio. You might want to have a specific window size to fit Exult and Studio on the screen(s) to easily drag'n'drop shapes. You are likely to want a bigger game area in this case, too.
![ExultnStudio](https://user-images.githubusercontent.com/3313896/149223045-1a425a87-0886-4131-adbe-475782c0b9bf.png)

**Comment by Dreded** [comment]
> I don't think people have an initial setup issue.

YouTube and reddit would disagree, Ill try and find a LetsPlay where the person figures this out on screen... they typically give up and go "Good enough"

I myself only just figured out after playing with the settings for 30minutes the best non cheating way for a 1440p monitor is...
![2022-01-12 13_51_45-Greenshot](https://user-images.githubusercontent.com/3213678/149228814-ed9ff146-ddf5-48a0-81ad-58dc644e0778.png)

also sorry I didn't word my initial question correctly, as a player who wants the original experience what's the use case? I wasn't suggesting to do away with it just make it a "I know this will allow me to see more of the world than I am supposed to" sort of gate to the option.

What I think I would like to see for modern monitor support is Display Mode Locked to Native Desktop resolution when Full Screen is selected and AR Correction Locked... to my eyes at these 1080P + resolutions Point scaler is far far superior so have that as the default, then default the Scaling size too based on current resolution.

In addition to that allow the status bars to be vertically listed on left or right side instead of at the bottom so that they take up some black space.

I know this sounds like a lot of changes but something needs to be done to modernize this... I would think very few want a default 640x480 experience further making it worse by allowing the monitor to stretch in a substandard way.

**Comment by Dreded** [comment]
the AR Correction is as simple as making it sound substandard... "Disable AR Correction"... "are you sure?"

**Comment by DominusExult** [comment]
That's all stuff for a different issue.

**Comment by Dreded** [comment]
I personally disagree as the one that wants to see a big change its all the same issue, but can understand others do not want to see the same sweeping change so doing the work twice may make sense, ill open a new issue.

**Comment by DominusExult** [comment]
This has been fixed a while ago
