### ISSUE TITLE
Exult Studio does not save "Frame Names"

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#121]
With the switch to GTK+3 we seem to have lost the ability to save "Frame Names" of shapes.
-double click a shape
- select "Frame Names"
- go to "Frame Names" tab
- add names for frames
- save
- restart Exult/Exult Studio -> Frame Names have not been saved. 

At first glance it seems as if shape_info.txt is not being saved to the patch folder.
@Dragon-Baroque and @marzojr any ideas what goes wrong?

**Comment by Dragon-Baroque** [comment]
The problem occurs much sooner : 
Open the Shape Editor on any Shape without Frame Names, Check "Frame Names" in the main panel of the Shape Editor, Switch to the Frame Names tab, Add names, click on Add, click on OK.
Reopen the Shape Editor on the same Shape, the Frame Names are lost.

This is the same for Content Rules, Frame Flags, Frame HPs, Frame Usecode, Object Paperdoll, Brightness and Warmth.

The problem comes from the transfer back from the GTK treestores into the `Shape_info` vector objects. The Vector of `Frame_name_info` is properly populated by the `Update_framenames` function, but is immediately erased by the `clean_invalid_name_info` in Exult_Studio::save_shape_notebook [ mapedit/shapeedit.cc ]. 
All the `clean_invalid_..` functions run `clean_vector`, but the `clean_vector` [ shapes/data_utils.h ] erase condition is wrong.
It is written as 
 `return elem.is_invalid() || !elem.have_static();`
It should be written instead as
`return elem.is_invalid() && !elem.have_static();`
 by comparison with the code of `clean_vector` prior to commit 9e1a5d356.

I shall provide a Pull Request as soon as I complete retrieving my lost GitHub credentials.

Sincerely
Dragon-Baroque

**Comment by marzojr** [comment]
Can anyone confirm if it is working now?

**Comment by DominusExult** [comment]
Finally just tested it and it works. One might argue that setting "all qualities" as the default could be a good idea.
