### ISSUE TITLE
Exult Studio "can teleport" NPC Flag

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#122]
from the forum http://exult.info/forum/viewtopic.php?f=1&t=1791265:
Been awhile since I've posted but as of late I've been back into doing some building of Glimmerscape2. I've been creating some new NPC shapes but have noticed some strange behaviour with the Exult Studio that I'm not sure if it is intended or not.

The situation is on some of the new NPC shapes I created, such as shape 1559, the "NPC flags" checkbox is always checked. The object class is "Monster". This creates the "NPC Flags" tab and the "Can teleport" box is checked in this tab. I've unchecked "Can teleport" and did multiple saves of shape info, save map, save all, but if I close Exult Studio and open the shape again the "Can teleport" is checked again. If I remove "NPC flags" on the main object tab and repeat the same process as above it rechecks "NPC Flags" on the object and "Can teleport" is checked again. If I check another "NPC Flags" box, such as "Cold immune" it saves as expected. If I check a new flag and uncheck "Can teleport" the new flag check box saves as expected but "Can teleport" remains checked no matter what I do.

I've found this "Can teleport" occurs when the "Monster" extra flag is checked. If I uncheck this NPC flags work as I would expect. If I want the "Monster" extra flag enabled and change the class from "Monster" to "Human" the issue does not occur.

Is it intentional that classes of "Monster" with extra flag "Monster" should always be able to teleport as a flag, or am I doing something strange that could be contributing to this behaviour?

**Comment by drcode1** [comment]
Pretty sure it's a bug, since most monsters can't teleport.  When you 
start the game, does the monster actually teleport (like mages, I think)?

I want to look at it, but first need to be able to build again.

**Comment by drcode1** [comment]
Whew!  I finally got exult to compile, but I had to upgrade Ubuntu.  I 
tried changing the "Can teleport" flag on an existing shape, and it 
seems to work okay.  But I can't recall how to create a new shape.

I have a feeling the problem has to do with this bit of code I found 
that gets executed when reading in files:

         // We already have monster data by this point.
         Monster_info *minf = info.monstinf;
         if (minf) {
             // Deprecating old Monster_info based flags for these powers:
             if (minf->can_teleport())
                 info.actor_flags |= Shape_info::teleports;

So I wonder if the user created the shape with an older version, and 
he's stuck with the old monster-info flags.  If I can figure out how to 
create a new monster, I'll see if that might be the case.

**Comment by DominusExult** [comment]
Hmm, yes. He explicitly states in the other thread about the frame names that he used a very old version initially.

**Comment by drcode1** [comment]
I'll try to fix it.

**Comment by marzojr** [comment]
> Hmm, yes. He explicitly states in the other thread about the frame names that he used a very old version initially.

Did he click the "fix old shape info" button in the tools menu?

**Comment by DominusExult** [comment]
I don't know but I'll point him to that!

**Comment by Donfrow** [comment]
I have tried the "fix old shape info" in the Tools menu. No change in behaviour when trying to disable the "Can teleport" NPC flag.

**Comment by Dragon-Baroque** [comment]
I think I have it, following @drcode1 proposal.
I can reproduce @Donfrow problem by taking his Glimmerscape Mod from SourceForge and installing it as a Mod of SilverSeed, because the Wisp - Shape 1298 - has the can teleport flag set from the monster.dat, not as an Actor info.
1. Run Exult Studio against SilverSeed + Glimmerscape.
3. Open the Wisp, shape 1298, with the Shape Editor. It has no proper NPC flags, thus the Monster flag to Actor flag translator does not run.
4. Give to that Shape a NPC Flag check + NPC flag such as Is Goblin.
5. Save and Exit Studio. 

Check that there is a now modified shape_info.txt with an actor_flags records for the shape 1298.

1. Rerun Studio on SS + Glimmerscape again.
2. Open the same Wisp with the Shape Editor. This time the actor info reader is invoked and it finds the monster info record, detects that it contains the teleport/summon/invisible flags and transfers them to the actor info. _Wrongly by the way, as it is written_
`info.actor_flags |= Shape_info::teleports;` but should be written 
`info.actor_flags |= (1U << Shape_info::teleports);` instead.
3. Notice that there are more flags set in the NPC flags than just the Is Goblin.
4. If you remove the Actor flags created by the Monster info with the Shape Editor, you only alter the Actor info record in shape_info.txt, not the original Monster info in monsters.dat, where the flags remain. Thus saving and rerunning Studio is hopeless : these flags remain.

At this point, I do not know what to propose :

1. Remove this obsolete flag transfer code completely. As far as I can tell neither FoV nor SS - GOG official distributions - nor any of the Exult-distributed Mods - IsleFaq, Keyring, LBJoin, CureCantra, SIFixes - use any of them. On the other hand, I have checked Glimmerscape, as above. I have not checked any of the other Mods that Exult does not distribute.
2. Secure the flag transfer code. First, of course, replace the `info.actor_flags |= Shape_info::teleports;` and all by `info.actor_flags |= (1U << Shape_info::teleports);` and equivalents. Second, while doing this, remove the flags from the Monster info, and mark the Actor info and the Monster info as modified, so that they would be saved. 

Sincerely
Dragon Baroque

**Comment by Dragon-Baroque** [comment]
How to use the commit with Glimmerscape 2 :
Run Studio against SilverSeed & Glimmerscape2 in console, because Studio issues warnings to stderr like
`Shape 1298 is a monster that can teleport, teleport flag moved from Monster info ( monster.dat ) to Actor info ( shape_info.txt ) as NPC flags.`
when you click on any Shape of the `shapes.vga` right page.
Write down the Shape numbers, Save All, then Edit one at a time the warned Shapes, they will have acquired a NPC Flag among can_summon, can_teleport, can_be_invisible, but these flags are now regular shape_info.txt flags, they can be deleted.

**Comment by Donfrow** [comment]
Tried this out on my mod and it worked. Updating the NPC flags is now behaving as expected. Thanks!

**Comment by Dreded** [comment]
Shouldn't this be closed?

**Comment by DominusExult** [comment]
yes :)
