### ISSUE TITLE
Question about shape frame pixel value and palette indexing for RGB value.

### ISSUE THREAD

**Issue by pantinor** [exult/exult#125]
Not an issue but a question rather, I am playing around with the U7 map and shape files on my own and am at the processing of the pixel bytes in the SHAPES.VGA file for a shape frame scan.  The question is about what this pixel value represents.  Assumed it is a index into the rgb palette table (ie 768 len byte array), is that right?  The Exult code seems to show that this value is processed along with the xform palette, so maybe kernel is doing that rgb lookup.. but am thinking instead to do the lookup with a buffered image to set the RGB value at an x and y coord with a helper like this below.  Any clarification on that pixel value and palette question is appreciated.  Thanks.

`  
public int rgb(int idx) {
	byte r = palette[3 * idx];
	byte g = palette[3 * idx + 1];
	byte b = palette[3 * idx + 2];
	int rgb = (r << 24) | (g << 16) | (b << 8);
	return rgb;
}
`

**Comment by marzojr** [comment]
That is the basic idea, yes; each byte in the (decompressed) shape is an index into the active palette. Palettes in U7 are stored in 6-bits per channel (but still using one byte per channel), and should be scaled back to 0-255 range for display; Exult uses basically this formula:

```c++
	channel_out = (channel_in * 255L) / 63;
```

(with some slight edits to remove brightness stuff; full version is Get_color8 in iwin8.cc).

For most shapes, there is a few ranges of colors at the end that undergo palette rotation. These palette rotations are global, and affects all shapes at the same time; but the basic idea is that the colors are permuted cyclically in each range.

Some shapes are *translucent*; for these, the last few palette entries are an index to a xform table (255 = xform index 0, 254 = xform index 1, etc.) *instead of* being rotated (translucent shapes do have some of the rotation ranges, but not all). Each xform table is a lookup table: you take the pixel value under the shape where it is translucent and use it as an index in the corresponding xform table. The result of the lookup is the pixel value to use when looking up the RGB value for the shape.

**Comment by pantinor** [comment]
Thanks for the information.  I tried using the channel scale back routine, but still having some issue resolving the pixel index to the correct rgb value from the palette.  This is the code am using below, maybe you can see something I missed.  When running it, the png images are not recognizable as any shape or fixed base image on the map, although I think the algorithm is accurate.  Even with the rgb color indexing being misaligned I expected to see some indication of the shape.  Thanks again for any pointers.
https://github.com/pantinor/u7-java/blob/main/src/test/java/ultima7/MapRender.java
