### ISSUE TITLE
Exult Studio: Cannot create NPC past 355

### ISSUE THREAD

**Issue by Donfrow** [exult/exult#126]
When running Exult and then opening Exult Studio and creating NPC's in Exult Studio (Edit -> Create NPC) for Serpent Isle the Exult Engine crashes.

Exult version 1.7.0git
Built at: Nov 28 2021 00:24:47

I cannot find where the version number is for Exult Studio.

In Exult Studio, the Usecode that comes up in the editor is 0x400 which is for the Avatar. Per the forum -356 and -357 are used for party and Avatar so suspicion is it is related to that. When this occurs I am using ES to create my mod so the patch folder is in use and it is not the standard Serpent Isle/Silver Seed. Forum thread [here](http://exult.sourceforge.net/forum/viewtopic.php?f=1&t=1791269&sid=07429efb2f894404e46514dfa4735fb6).

stdout and stderr does not seem to have anything out of the ordinary when this occurs for me, but output is as follows:

stdout (omitted start up log data) :
Opening digital SFX's file: "<DATA>/sqsfxsi.flx"
Gamedat identity SILVER SEED
Reading usecode file.
Loading <DATA>/exult_si.flx...
Loading default keybindings
Opened socket for Exult Server on port 50587
Cheats enabled.
Executing: exult_studio -x data -g serpentisle &
Game paused
Connected to client

stderr 
Could not open file '.\forgeofvirtue\static\mainshp.flx
Could not open file '.\silverseed\static\mainshp.flx
Could not open file '.\serpentbeta\static\mainshp.flx
Warning, trailing slash in path: "<BLACKGATE_STATIC>\"
Warning, trailing slash in path: "<SERPENTISLE_STATIC>\"
SDL Reports 640x400 16 bpp and 32 bpp windowed surfaces are not OK. Windowed scalers may not work properly.
SDL Reports 1200x900 16 bpp and 32 bpp windowed surfaces are not OK. Attempting to use 16 bpp. anyway

**Comment by i30817** [comment]
Are you using the ubuntu ppa?

A while ago i disabled building exult studio gimp plugin because it was not building in gtk3, i thought that was meaningless (the plugin was just for opening the files outside) but it may be causing this crash if the studio does use it directly. Do you have the file `usr/lib/gimp/2.0/plug-ins/u7shp` in your system?

**Comment by DominusExult** [comment]
The gimp plugin is not used at all by Exult Studio. It's purely there to allow Gimp to open shp files.

@i30817 you should revisit the plugin build. It *should* just work and if not please open an issue about it.

**Comment by Dragon-Baroque** [comment]
Regarding the Gimp plugin, I, Dragon-Baroque, may be the culprit.
When I migrated Exult Studio to GTK3, I left two components aside :

1. The Gnome Thumbnailer,
2. The Gimp Plugin.

First, the Gimp plugin cannot be migrated to GTK3 because Gimp itself will not be migrated to GTK3 until Gimp 3.0. My up to date Fedora Linux still distributes a Gimp 2.10 using GTK2. Therefore to build the Gimp plugin, one would need to expect two different GTK requirements in configure.ac and some tricky changes in the Makefile.am.
Moreover, I noticed that the u7shp executable is an exception in that it is to be installed somewhere into /usr, which I am not ready to allow. The rest of Exult and Studio is installed into my /home.
Finally, the Exult Studio no longer uses it to exchange pictures with Gimp, it exports and imports PNG files instead.

As for the Gnome Thumbnailer, I wonder what it does, especially considering the I do not often leave the KDE Plasma desktop.

**Comment by i30817** [comment]
gnome thumbnailer is a plugin for gnome framework used by nautilus (and other things like 'tracker' i think, which i always disable), which shows the file as a image of the contents. Resuming it's like that horrible file database which you sometimes encounter in zipped files that came from zipping windows directories which have a hidden file for thumbnails.

**Comment by Donfrow** [comment]
From previous comments it sounds like it would be unrelated to what I'm running into, but no I am not using those.

**Comment by marzojr** [comment]
Is this still an issue in current git?

**Comment by Donfrow** [comment]
I installed the latest version:

Exult version 1.9.0git
Build Architechture: x86
Built at: Mar 25 2024 01:16:10
Compile-time options: USE_TIMIDITY_MIDI, USE_FMOPL_MIDI, USE_MT32EMU_MIDI, USE_EXULTSTUDIO, HAVE_ZIP_SUPPORT
Compiler: GCC 13.2.0

I haven't touched this in awhile, but I went and tried to create a new NPC (or clicking the NPC folder in Studio) and it crashes Exult.

stdout and stderr look pretty much the same as my original post:

stdout
Opening digital SFX's file: "<DATA>/sqsfxsi.flx"
Gamedat identity SILVER SEED
Reading usecode file.
Loading <DATA>/exult_si.flx...
Loading default keybindings
Opened socket for Exult Server on port 54795
Cheats enabled.
Executing: exult_studio -x data -g serpentisle &
Game paused
Connected to client

stderr
Could not open file '.\forgeofvirtue\static\mainshp.flx
Could not open file '.\silverseed\static\mainshp.flx
Could not open file '.\serpentbeta\static\mainshp.flx
Warning, trailing slash in path: "<BLACKGATE_STATIC>\"
Warning, trailing slash in path: "<SERPENTISLE_STATIC>\"
SDL Reports 640x400 windowed surfaces are not OK. Windowed scalers may not work properly.
SDL Reports 1200x900 windowed surfaces are not OK. Attempting to use 16 bpp. anyway

I tried it with a non-patched version and it worked to open the NPC window in the editor, but that didn't have >355 in it so couldn't say if it was my patch folder causing the issue or if it was not having 355 NPC.

In the crashing version, in Studio the Exult new NPC window shows usecode 0x3590 instead of the 0x400 of my original report.
