### ISSUE TITLE
.clang-format wider columns

### ISSUE THREAD

**Issue by Dreded** [exult/exult#132]
I propose to allow ~~160~~ 120 columns while formatting... or even wider.. but ~~160~~120 is reasonable.

short columns promote lazy variable names.. we running out of screen space in 2022?

didn't want to do a pull request if for some reason its not a desired outcome... but the change can be found here...

https://github.com/dreded/exult/tree/change-clang-format-for-wider-columns

**Comment by Dreded** [comment]
perhaps 120 might make more sense? here is a screenshot with vertical lines at 80,120 and 160 on a 1080p monitor.
![lines](https://user-images.githubusercontent.com/3213678/149589679-6bcc27fb-a25a-4dd7-b24c-d12be4813beb.png)

Benefit of 120 over 160 is that in 1440p you can fit two views side by side with enough room left over for the file browser etc. at 1080p 120 almost fits 2 views without a file browser(fits about 115)
If you remove the file browser at 1440p then 160 just fits for 2 side by side views.

**Comment by Dreded** [comment]
120 also has a positive effect on file length(line count) for stuff already formatted. I think the  Right looks a lot cleaner than the left, 120 would fit 99% of use cases(even at 1080p this all fits on screen without the file browser)
![lines2](https://user-images.githubusercontent.com/3213678/149592085-c7b6cb37-f1e3-46e9-b82b-8930edbaaebe.png)

**Comment by marzojr** [comment]
That depends on monitor size, resolution, pixel density, font size, and other factors. On my desktop, I can't have lines longer than about 100 character without needing scrolling on diff view, despite having 2560x1440 resolution, because of pixel density -- I need 125% scale on the monitor or the fonts become too tiny. On my laptop, more than 80 characters lead to scrollbars on diff view because of the smaller screen.

Using 80 characters is a safe default value.
