### ISSUE TITLE
SI: Dreamrealm fight Batlin vs Avatar

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#152]
In the dreamrealm you get to the arena where Batlin dreams of defeating the Dreamavatar.
In the original he wins and then both "teleport" away from the dreamrealm.
In Exult the Dreamavatar doesn't die/falls unconscious and Batlin eventually teleports away.

In the savegames climb the north stairs and walk on the balcony to the north seats.
[exult218si.sav.zip](https://github.com/exult/exult/files/8081244/exult218si.sav.zip) <- Exult savegame (rename to sav)
[GAME00.U7.zip](https://github.com/exult/exult/files/8081279/GAME00.U7.zip) <- Original savegame (unzip)

**Comment by marzojr** [comment]
The issue is with the way Exult implements polymorph shapes. In this cutscene, the "Avatar?" is actually a polymorphed bear (shape 0x12E polymorphed into 0x2D1). When Dream Batlin "kills" the "Avatar?", this fragment of usecode is called to turn the "Avatar?" into a corpse:

```dart
		if (qual == 0x0010) {
			var bear_list = find_nearby(0x12E, 40, MASK_NONE);
			for (bear in bear_list) {
				struct<Position> pos = bear->get_object_position();
				bear->set_polymorph(0x12E);
```
The call to `find_nearby` returns the bear in the original, but not in Exult, so the `for` never runs and the "Avatar?" is never killed. But there is an independent timer for Batlin to blast off, and so he does.

**Comment by DominusExult** [comment]
Blows my mind! Thanks for figuring this out

**Comment by drcode1** [comment]
Wow. That bug has been there a long time!
