### ISSUE TITLE
UI_close_gumps() doesn't work in usecode in "if (event == READIED)"

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#159]
Due to `USECODE_INTRINSIC(close_gumps)` in intrinsics.cc:2474 having the limitation `if (!gwin->is_dragging())` you can't use `UI_close_gumps()` in an `if (event == READIED)`. So far I have not found a workaround in a usecode script.
The check is most likely there for good reason!

Perhaps `USECODE_INTRINSIC(close_gumps)` needs some way to bool `gwin->drop_dragged` but adding that was a bit over my head.
OR we need another Exult only intrinsic that does a delayed `close_gumps`.

Quick way to test it is to alter the invisible ring code in the BG Keyring mod (content/bgkeyring/src/items/rings.uc).

(and of course same is true for `USECODE_INTRINSIC(close_gump)`

**Comment by drcode1** [comment]
I think it was there for a good reason, but I can't remember it! You 
could try removing the test, and then see what goes wrong.

**Comment by marzojr** [comment]
Hm. I tried out removing the check, and I immediately noticed one thing was broken: the black sword in SI. For reference, this is how its usecode starts:

```
void Func0326 shape#(0x326) ()
{
	var var0000;
	var var0001;
	var var0002;
	var var0003;
	var var0004;
	var var0005;
	var var0006;
	var var0007;
	UI_close_gumps();
```

So it should close gumps as soon as its usecode is called. Here are a few tests and the resulting behavior:

Test 1: with black sword readied in back scabbard slot: drag the black sword and drop it into the ground.
- stock SI: gumps are not closed when you start dragging it. It stays on the ground until gumps are closed; then it returns to the avatar.
- Exult with the check present: gumps are not closed when you start dragging it. It immediately returns to the avatar as soon as dropped on the ground.
- Exult with the check removed: gumps are closed as soon as you start dragging it. Since gumps are closed, it returns to the avatar as soon as dropped on the ground.

Test 2: with black sword readied in back scabbard slot: drag the black sword and drop it into the avatar's backpack, then drag  the backpack and drop it into the ground.
- stock SI: gumps are not closed when you start dragging either the black sword or the backpack. The black sword stays on backpack until gumps are closed; then it returns to the avatar.
- Exult with the check present: gumps are not closed when you start dragging either the black sword or the backpack. The black sword stays on backpack.
- Exult with the check removed: gumps are closed as soon as you start dragging it, and it cannot be dropped into the backpack.

Test 3: with black sword readied in back scabbard slot: drag the black sword and drop it into the avatar's backpack. Gumps are closed, then reopened. Then drag  the backpack and drop it into the ground.
- stock SI: gumps are not closed when you start dragging either the black sword or the backpack. The black sword stays on backpack.
- Exult with the check present: gumps are not closed when you start dragging either the black sword or the backpack. The black sword stays on backpack.
- Exult with the check removed: gumps are closed as soon as you start dragging it, and it cannot be dropped into the backpack.

Using rip/ucxt/wuc/rip to modify some usecode and running it in the original games, I can say the following things:

- Ready events
    - SI
        - The black sword: never generates ready events, usecode never runs.
        - Ring of invisibility (shape 296 frame 0) and helm of lights (shape 1013 frame 0): usecode is executed immediately.
        - All other items that generate ready events: usecode is only executed after gumps are closed. This matches the behavior of using a (delayed_)execute_usecode_array call to the shape's usecode, but with a different event.
    - BG: usecode is executed immediately.

- Unready events
    - SI
        - The black sword: usecode is only executed after gumps are closed. This matches the behavior of using a (delayed_)execute_usecode_array call to the shape's usecode, but with a different event.
        - All other items that generate unready events: usecode is executed immediately. Gumps cannot be closed by usecode during unready events.
    - BG: usecode is executed immediately. Gumps cannot be closed by usecode during unready events.

As it turns out, Exult matches BG behavior for unready events, but the original game allows ready events to close gumps. Exult does not match at all the behavior of SI except for ring of invisibility and helm of light. Most of the differences are not observable unless you *really* know what you are looking for, and are probably not worth emulating because the way BG does is simply better. Moreover, custom usecode can always emulate the SI way by having the ready/unready event call (delayed_)execute_usecode_array to call the custom usecode after gumps close.

Removing the check in UI_close_gumps breaks the black sword on both ready *and* unready events because Exult generates ready events for the black sword, which would cause gumps to be closed anyway because the black sword's usecode unconditionally closes gumps.

I am unsure how to proceed. Maybe the best option would be to document this, and maybe add an optional parameter that forces the gumps to be closed even in ready/unready events?

**Comment by marzojr** [comment]
After talking a bit with Dominus, I decided on adding two new intrinsics, `UI_close_gump2` and `UI_close_gumps2`, which work in these cases as well. I also updated the documentation to mention the limitations of the original intrinsics.
