### ISSUE TITLE
@KnightCaptain's pull requests

### ISSUE THREAD

**Issue by rofl0r** [exult/exult#17]
@KnightCaptain made some PRs in the last half year, that fixed numerous issues and added various improvements; but since the commits were unclean (whitespace issues, etc) they weren't merged as is, and he later just closed them all.
That's a bit sad, imo. Anyone working on getting them cleaned up so they can be merged before they will be forgotten ? @KnightCaptain : what's your plan ?

**Comment by DominusExult** [comment]
Yes, I'm nowhere able to handle that many pullrequests that have whitespace errors. I would just make a bigger mess.
But please don't give up ;)

**Comment by KnightCaptain** [comment]
The improvements I did were growing beyond the scope of SI Fixes. The last request was simply too large, and I cancelled it in part because I later found a minor error before it was accepted or rejected.

The changes have neither been lost nor forgotten. The work has become a still-private independent project called _The Conquests of Chaos_. I have posted a good amount of progress on the Phorum about it, including screenshots. At over 1,300 files, adding the GPL headers, whitespace cleanup, and bug fixing will be a significant task. It largely uses the folder structure and best practices I learned from SI Fixes, in the hopes it may someday become part of the default Exult installation.

**Comment by i30817** [comment]
So, it's a planned replacement of SI fixes? I hope that just like it, it someday ends up in the repo. I take advantage of the fact that exult builds the main mods in order to provide them easily to the ppa users.

Thought that already failed once, just fixed a error that had the Keyring mod invalid for about a year (because of a bad path directory, 'bgkeyring' instead of 'Keyring' with uppercase) that i hadn't noticed (sifixes was fine, because it uses a sane and sensible lowerpath name and the dir name is equal to the build result name).
