### ISSUE TITLE
Mods are no longer discovered on Windows

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#204]
Git bisect points at 05338a43 by @ceckak to being the culprit.

**Comment by ceckak** [comment]
I haven't dug into setting up a windows build environment yet, but will review the code and see if I can figure out what is going wrong.

**Comment by marzojr** [comment]
I see what is the issue. in modmgr.cc, line 548, U7exits is used to check if a directory exists. But the rework with sdlrwops makes it work only for files. This should also be breaking ES, as it checks for existence of directories on several places.

**Comment by ceckak** [comment]
Thanks for chasing that down.  I know part of the motivation for the change to `U7exists` was to ensure it finds Android resources as well as files.  I'm a little confused why it is working on Android (which is successfully finding mods); it may be that Linux platforms are capable of opening directories as files while windows is not?

In any case, I can probably resolve this by reintroducing the `stat()` check and fall back to the `sdlrwops` check if `stat()` doesn't find anything.

**Comment by DominusExult** [comment]
if you have some code you need to test out on Windows post your patch here and I can test in my VM.

**Comment by ceckak** [comment]
Here is a proposed fix.  Rather than pull the old `stat()` code in like I was originally thinking, this follows the current code by leaning on existing abstractions and calls `U7opendir()` to check for directories.  This is not the most efficient way to check for existence, but is nice from a maintenance/correctness perspective in that it explicitly checks whether the file exists for the U7 file abstractions.  If there are concerns about performance with this patch, It should be trivial to bring back the `stat()` code with the `U7open_in()` call as the fallback.

[make-sure-u7exists-can-detect.txt](https://github.com/exult/exult/files/8598278/make-sure-u7exists-can-detect.txt)
