### ISSUE TITLE
macOS: snapshot broken

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#230]
The snapshot is broken atm as it pulls in a harfbuzz dependency from another prefix than the glib provided in the snapshot. This it doesn‘t crash.

**Comment by DominusExult** [comment]
Seems that with 7a36171e it began somehow mixing my two prefixes. Need to further investigate

**Comment by DominusExult** [comment]
The problem is that my two-prefix build system is breaking once freetype is pulled into the Exult linking which then uses the one first found in my GTK3 prefix.
Why do we even need the Freetype libs in EXULTLIBADD in Makefile.am when only Exult Studio needs that? https://github.com/exult/exult/blob/master/Makefile.am#L146

@Dragon-Baroque @ceckak @marzojr

**Comment by Dragon-Baroque** [comment]
@DominusExult, a few thoughts.
- In Linux I can list referenced but unused shared libaries in an executable like `exult` by `ldd -u exult`. MacOSX ?
- Yes, FREETYPE2_LIBS should be removed from EXULTLIBADD.
- There are many tools in `tools/Makefile.am`, plus ucc and ucxt in `usecode` with unneeded references to libX11, libXau, libXcb. They use SYSLIBS which is set to libX11 in `configure.ac` with an explanation about Linux bugs 2129731 and 3139441 with a bug `Missing -lX11 in generated makefile` of Sourceforge Exult back in 2010. SYSLIBS can also be removed from `exult` and `exult_studio`.
- There is also a strange variable x_libraries in `configure.ac`.
- I get many warnings about Ogg and Vorbis during `autogen.sh`. Because the Ogg and Vorbis location scripts in `configure.ac` support the lack of `pkg-config` and then fallback on XIPH_PATH.. macros that `autoconf` finds rather outdated. Could we now safely require that `pkg-config` be present, and remove all fallback paths in `configure.ac` ?
- In Linux one can prevent unneeded shared libraries to show up in the reference list of an executable. One uses `LDLAGS=-Wl, --as-needed`. I admit that this is a lazy job to list too many shared libraries and rely on this option to discard them. But it works... What about MacOSX ?

**Comment by Dragon-Baroque** [comment]
Just posted Merge Request #232 making pkg-config mandatory in 1.9.
Has been accepted and merged by @marzojr, thanks.

BTW, I would like to awaken my issue #185 about cleaning up `configure.ac` instead of the present one, seems more relevant to me.

**Comment by DominusExult** [comment]
> I'll have to test for LDLAGS=-Wl, --as-needed and what the equivalent to ldd - u is on macOS.

I found no equivalent for either on macOS
