### ISSUE TITLE
1.4.9 final release?

### ISSUE THREAD

**Issue by bsiegert** [exult/exult#26]
I see that 1.4.9rc1 was released in 2016. Was there ever a final release for 1.4.9?

**Comment by DominusExult** [comment]
1.4.9rc1 is even much older, 2016 was only the date the SF files were imported to github. There was never a 1.4.9 release as there were important bugs that needed fixing. The 1.4.9rc1 is *NOT* recommended.

**Comment by bsiegert** [comment]
pkgsrc has 1.4.9rc1 as a package: http://pkgsrc.se/games/exult. What are you suggesting to do? Downgrade? Or package a more recent snapshot?

**Comment by DominusExult** [comment]
build from source, that is always the best for Exult.

**Comment by bsiegert** [comment]
I for one would be glad for a release, even if it's merely a snapshot of the current state. That would make it easier to provide packages for Exult.

**Comment by DominusExult** [comment]
I'm still hoping for @marzojr  to add the way better intro and for @drcode1 to find the culprit for the crashes I can reproduce but he can't :(

**Comment by rofl0r** [comment]
> to find the culprit for the crashes I can reproduce but he can't :(

the joys of C++ ...

**Comment by i30817** [comment]
Do you do ubuntu? I have a ppa here: https://code.launchpad.net/~exult-team/+archive/ubuntu/exult-daily

**Comment by rofl0r** [comment]
>>    to find the culprit for the crashes I can reproduce but he can't :(

> the joys of C++ ...

actually we've come a long way. modern compilers allow to compile C/C++ code with UBSAN and ASAN enabled, this could be a huge help to find the code that writes to memory it's not supposed to write to. ever tried that ?

**Comment by marzojr** [comment]
Can you file a bug report or pull request for this OOB? I think I may have already handled this locally, but my computer is off and I can't check right now.

Sent from Yahoo Mail on Android 
 
  On Thu, May 17, 2018 at 18:55, Adam Nyzio<notifications@github.com> wrote:   I ran ASAN about a year ago or so on Exult for both BG and SI. It was
fairly clean. I found one crash that was actually due to a bug that was
hanging me up in SI during normal gameplay. I was also able to tease out a
UAF in a timer based map garbage collection routine that was hard to
reproduce so I was never able to come up with a fix. There is also an OOB
memory access in the credits screen that I never got around to committing a
patch for:

--- a/txtscroll.cc
+++ b/txtscroll.cc
@@ -56,7 +56,7 @@ TextScroller::TextScroller(const char *archive, int
index, Font *fnt, Shape *shp
 shapes = shp;
 U7object *txtobj;
 // Hack to patch MAINSHP_FLX.
- if (!memcmp(archive, MAINSHP_FLX, sizeof(MAINSHP_FLX) - 1))
+ if (!strncmp(archive, MAINSHP_FLX, sizeof(MAINSHP_FLX) - 1))
 txtobj = new U7multiobject(archive, PATCH_MAINSHP, index);
 else
Im sure there are more, but building and playing under ASAN slows things
down quite a bit, although the nostalgia factor is much higher when you are
playing the game and its lagging like it used to on my 386 back in the 90s

-Adam

**Comment by rubyFeedback** [comment]
Could a new stable minor release be released?

I understand that this may not be changing things hugely but any small
up-to-date release may help a little bit.

**Comment by bsiegert** [comment]
@DominusExult Look, a new release does not need to be perfect nor bug-free. Simply releasing what you have, non-reproducible crashes or not, is strictly better than only having a three-years-old release candidate that you do not recommend anyone use. 

If the current code is better than your last release, just make a new release. You can note the unsolved problem in the release notes in some kind of "Known Issues" section.

**Comment by DominusExult** [comment]
Yes, unfortunately, we are currently at an impass. We have a good branch of Exult that eliminates the crashing but merging it will probably cause other bugs and needs just a little testing.

**Comment by flamewing** [comment]
In have actually been doing a lot of work on Exult locally. Unfortunately, what I need the most is time to finish up everything, and more time to test.

I need to push at some time, after I can make sure my changes did not break anything obvious.

**Comment by marzojr** [comment]
I have actually been doing a lot of work on Exult locally. Unfortunately, what I need the most is time to finish up everything, and more time to test.

I need to push at some time, after I can make sure my changes did not break anything obvious.

**Comment by DominusExult** [comment]
Always here to test things out :)

**Comment by drcode1** [comment]
I would like to get that merged. I played through BG with it, fixing
problems along the way. Then about 1/3 through SI, and it's doing fine.

**Comment by rofl0r** [comment]
> I would like to get that merged.

> Unfortunately, what I need the most is time to finish up everything, and more time to test.

that sounds quite clear to me: what @marzojr has in his local branch is experimental code lacking polish.

but as far as the master branch of this repo is concerned, it would indeed be helpful to just add a git tag (beta version) to what's there so distros can ship something recent.

**Comment by marzojr** [comment]
It is not that it is lacking in polish, but it is high in volume, and we don't have tests.

And while a good chunk of what I did is automated clang-tidy replacements (with manual double-checking), not all of it is: and although a lot of what remains is mostly safe, and improves memory management (replacing C arrays with std::arrays or std::vectors, more use of RAII to avoid resource leaks, etc), there are a few that may have drastic consequences.

 I will merge everything into a new dev branch and push it, maybe over the weekend, so that more testing can commence.

And the git tag would not help either: most of the changes that fix the memory issues are not in the master branch, local or otherwise.

**Comment by marzojr** [comment]
I merged to a new development branch based on master. I am preparing a build using sanitizers to track the several bugs I already encountered on the branch; it is definitely not ready to be merged to master yet.

**Comment by DominusExult** [comment]
I'm in the process of preparing a release of master, without the fixes for the rogue object files that cause crashes.
Reasons:
1. Marzo's branch would be preferred but it needs more testing and it cuts off old Windows versions.
2. it's been ten years and that was only a RC :)
3. we really should have a new version in linux distros

@drcode1 any chance you could take a look at https://sourceforge.net/p/exult/bugs/2043/ ?
That would be a nice last fix before a release but we can go without it :)

And yes, I'm hurrying this a bit and ignoring a lot of bugs. Because everytime I looked to hard at bugs a release was postponed... And right now I have time to prepare it.

I hope you are all healthy and stay that way!!!

**Comment by drcode1** [comment]
It's the 'dont_pause' option.  If I set it to 'yes' in exult.cfg, things 
work correctly.  The default is 'no'.  The simple test I'm using is to 
open up inventory and try to give someone food.  If it's 'no', they 
won't respond until you close the gumps.  Am I getting this right?

So I could just set the default to 'no'.

Are we going to integrate the 'smart-pointers'?  I think that's what I 
have my development set to.  It's been a long time!

**Comment by DominusExult** [comment]
yes, setting it no as default would be the big first step, but at best we would need a fix so that "yes" triggers giving food and other things (like placing items on penumbra's door mat), regardless of "dont_pause" setting.

Marzo's merged-devel is what we should go for after the release and merge it into master, so it gets way more testing.
it's a "disruptive" branch as it kills off older operating systems and that's why I think we should have a release even though we still have crashes due to the pointers.

**Comment by drcode1** [comment]
I wonder if we should merge the smart-pointers before the release.  I 
played through BG with it, and about half-way through SI (before I got 
bored).  Seems stable.

**Comment by DominusExult** [comment]
I'm not sure if we could get the smart pointers only changes into master. I *think* these already relied on some c++ standard that would mean cutting ties with older Windows versions.
@marzojr knows best :)

**Comment by drcode1** [comment]
The gumps 'pause' change is easy, though I have to figure out how to 
switch back to 'master' in my work area.  (Not exactly an expert with 
'git'.)

**Comment by DominusExult** [comment]
git checkout master :)
But don't forget to stash if you have uncomitted changes.
Do you think you can add this fix? Otherwise I will just go ahead with releasing :)

**Comment by drcode1** [comment]
I just did a new clone from master, so I can make the change in a day
or two.

**Comment by drcode1** [comment]
I'm trying to remember how the original worked (and too lazy to try to 
run it in dosbox).  If you open a gump and feed a party member, I'm 
pretty sure he responds immediately.  But do the gumps close?  Or remain 
open?

**Comment by DominusExult** [comment]
Just tested :)
the party member responds immediately, but the gumps stay open (otherwise people would have thrown a fit if they'd have to open the gumps again for each complaining party member).

The closing gumps is best tested with Penumbras house opening. The savegame attached is right before that. You have to place the hammer on the ground on the golden sign.

[exult70bg.sav.zip](https://github.com/exult/exult/files/4458691/exult70bg.sav.zip)

**Comment by drcode1** [comment]
Just tried dosbox myself to confirm, and, yes, everything halts when 
gumps are open, but the NPC's respond when you feed them. This makes me 
think that we should keep 'gumps_dont_pause_game' as 'no' for the default.

Exult is acting inconsistent:  In SI, you'll hear the 'eating' sound, 
but the text doesn't show until you close the gumps.  So that's wrong.  
But in BG, it works correctly!

So, I need to figure out again how to display the Usecode trace 
messages.  I have a feeling something works differently in SI and we're 
not handling it.

**Comment by DominusExult** [comment]
Yes, for a soonish release we need to set the default back to gumps pause games. But preferably we would need to have Exult close the gumps even when they don't pause the game to avoid these issues.

configure has the option --with-debug=no|messages|symbols|full|extreme
I think messages are enough but at least with full you get a good output of usecode

**Comment by drcode1** [comment]
That does seem to be the default now.  I wish we didn't have the double 
negative. :-)  So 'dont_pause' is set to 'no' by default, and we do pause.

I think this is correct.  I just tried SI in Dosbox.  It pauses, and you 
don't see the NPC's response until after you close the gumps.  I ran 
Exult with the messages turned on, and the usecode is different in SI.  
Instead of saying the response immediately, it's scheduled in the 
queue.  So I think we're doing everything right.

You might check 'gumps_dont_pause' in your .exult.cfg to see if it's set 
to 'no'.

**Comment by DominusExult** [comment]
so, we should just leave the incorrect behavior when gumps don't pause games?

**Comment by drcode1** [comment]
I think so.  It's a feature Marzo added, and it's normally 'no'.

**Comment by DominusExult** [comment]
So, version 1.6 has gone live yesterday, a day late for The Black Gate's 28th anniversary :)

Btw. @wench introduced this gumps feature back then.

**Comment by drcode1** [comment]
Woohoo!
