### ISSUE TITLE
Single Sound Effect repeats on Energy Field

### ISSUE THREAD

**Issue by KnightCaptainU7** [exult/exult#268]
The Energy Field shape, 768 in SI, is set to "Single Sound Effect" to match when it is first created. But the sound repeats over and over. I don't believe that is how it worked in the original game.

Steps to recreate:
Start a new game and teleport to Vasculio's area. Or drop one in via ES.

**Comment by DominusExult** [comment]
Actually this behaves as the original. Simple steps to reproduce is via the energy field spell (no need to travel to Vasculio).
One could argue that this is annoying, though, but that's a whole world of grief when you go through all SFX.

**Comment by KnightCaptainU7** [comment]
In testing via DOSbox, once the shape is in its final frame the related sound effect stops. In Exult, it just repeats over and over.

Is this something closed as wontfix? If so, I can disable the related sound in my mod.

**Comment by DominusExult** [comment]
I've reopened it.
I think what happens and why I thought we were doing it correctly was that, as you said it stops when the energy field is complete but then starts again when the field goes down again.
And this happens when you cast the field but it doesn't go down when it is done by an egg.

**Comment by DominusExult** [comment]
currently sfx are dehardcoded and editable in shape_info.txt (so in a mod you can turn that sfx off completely).
But the `%%section shape_sfx` does not have the option to limit the frames that play the sfx. That would need an extension or another `%%section shape_sfx` like section.
@marzojr what do you think?

@KnightCaptainU7 can you give me the exact coordinates (or rather close so I'm not on it) for an energy field to test in the original and Exult?

**Comment by NotStanley4330** [comment]
I think I have this one fixed! I decided the easiest way was to extend the ```%%section shape_sfx``` section to have a field I have called halt_frame. Now the section is formatted as such:
```
:shapenum/sfxnum/delay/range/rand/extra/halt_frame
```

I added the necessary functions and lines to read this in and to check for it. Here is the new behavior of the energy field:


https://github.com/exult/exult/assets/44741162/43838d23-7980-4403-ae1a-ab39127da612

compared to how it currently behaves:

https://github.com/exult/exult/assets/44741162/e4670c0a-7bc3-46ec-ad1c-21a16a36365d

I don't think this will break anything, but if it does let me know. I created [this PR](https://github.com/exult/exult/pull/483) for the fix.

**Comment by DominusExult** [comment]
That was fast! Thank you!

I am wondering something else but related since you dove into the sfx code.
I think we have something to control the sfx volume (some delta or so) but don't really use it. Can you confirm this?
Because that could be a good candidate for another shape_sfx section, to be able to lower the volume on some sfx (surf is a prime candidate that annoys many people).
It's just something that came to my mind right now.

**Comment by NotStanley4330** [comment]
I can look into it! I don't remember seeing it but I was pretty focused on getting the halt frame thing implemented so I'll pour through the sfx stuff and find it. Would definitely be a good thing to implement because a ton of the sfx are really loud and annoying lol.

**Comment by marzojr** [comment]
I have looked at the original games in DOSBox. And I found that this:

> In testing via DOSbox, once the shape is in its final frame the related sound effect stops. In Exult, it just repeats over and over.
>
> Is this something closed as wontfix? If so, I can disable the related sound in my mod.

to be utterly false. The sound never stops; there are occasional lulls, but it will continue repeating forever. At best, we should be implementing some sort of random delay, but it should not be stopping.

**Comment by marzojr** [comment]
Also, it seems like the SFX changed from BG to SI -- in BG it was some sort of explosion, in SI it is something else. Maybe SFX 8?

**Comment by NotStanley4330** [comment]
Yeah I decided to go test this in Black Gate... this is horrible:

https://github.com/exult/exult/assets/44741162/182b1855-bfdd-4619-b9b8-accdca44f24d

**Comment by NotStanley4330** [comment]
It also appears to use a very different sound in exult than in DOSBox:

https://github.com/exult/exult/assets/44741162/2e32177b-5e7d-4219-9a9a-f12773ef1c49

**Comment by NotStanley4330** [comment]
And here is the effect in serpent isle now updated with a chance of 40:

https://github.com/exult/exult/assets/44741162/aac927af-47cb-41b0-8eac-77f85b8c3db2

It would appear that to mimic the original behavior the halt_frame things I added are entirely unecessary. I could just rip those out entirely if you think I should @marzojr

**Comment by NotStanley4330** [comment]
> I am wondering something else but related since you dove into the sfx code. I think we have something to control the sfx volume (some delta or so) but don't really use it. Can you confirm this? Because that could be a good candidate for another shape_sfx section, to be able to lower the volume on some sfx (surf is a prime candidate that annoys many people). It's just something that came to my mind right now.

So it appears that the function to play a sound effect does have a volume parameter:
```
channel = Audio::get_ptr()->play_sound_effect(sfx, last_pos, volume, 0);
```
But we seem to only ever blast it at the highest possible volume:
```
const int volume = AUDIO_MAX_VOLUME;    // Set volume based on distance.
```

This should be fairly simple to fix, as I can either add another option to ```%%section shape_sfx``` or replace the ```halt_frame``` one to be used as a volume value.

**Comment by NotStanley4330** [comment]
RE: Indvidual sfx sounds, I was able to implement something simple that seems to work pretty well. I currently have the ```%%section shape_sfx``` portion of ```shape_info.txt``` formated as such:
```
:shapenum/sfxnum/chance/range/rand/extra/volume
```
given that the halt_frame functionality seems to be unnecessary, I stripped it out on this branch (I kept it on another branch in case we wanted to keep it for whatever reason). This volume should be expressed as an integer from 0-100, for percentages of the max volume. This is calculated as such before being sent to the ```play_sound_effect``` method:
```
const int  volume = static_cast<int>(AUDIO_MAX_VOLUME * (sfxinf->get_volume() / 100.0));
```

To test this out I modified all surf sfx to play at different volumes. First 40 percent, and then 20 percent. Here are the results.

-100% volume (baseline)
For this one I just didn't add a volume value and recorded to get a baseline. Here is video of that:

https://github.com/exult/exult/assets/44741162/1a498ef9-47e0-40fa-81d1-239cba12e045

I uploaded the audio to audacity to be able to compare and make sure I wasn't imagining any change at 4am. Here is the 
plot analysis of that audio:
![image](https://github.com/exult/exult/assets/44741162/5f97b09c-87fc-46d6-8f0b-1c7f285a8ed8)

-40 percent
For this one I added the volume option to all listed surf sfx and recompiled. Here is the video of that in action:

https://github.com/exult/exult/assets/44741162/c2b44410-4f81-4074-b366-9057134d3792

And the plot analysis:
![image](https://github.com/exult/exult/assets/44741162/4d95437b-258e-4a15-87e1-67c7452cdcae)
This plot looks fairly similar to the first one, but there is a definite dip in the 1 kHz band from around -45 dB to about -51 dB.

-20 percent
I just modified all the volume values to 20 here and re-built exult. Here is the video:

https://github.com/exult/exult/assets/44741162/c9f7c78c-3c29-4bcd-8997-58dd57f91a62

And the plot spectrum analysis:
![image](https://github.com/exult/exult/assets/44741162/18ce32d2-9f05-4f7e-a6e4-0f24d73c6129)
Again we have another drop, this time to below -57 dB.

This is basically a long winded way of saying the change seems to work! I will hold off on doing a PR for a bit because I don't want to just arbitrarily determine volume percentage volumes for all the sfx lol.

**Comment by NotStanley4330** [comment]
> can you add a patch for it? I would love to try it out :) And the surf seems to need even more drop of percentage (maybe even down to 5%?). Figuring out the percentage could likely be a group effort, most are annoying when repeated but lowering the noise significantly is welcome. Maybe even the fire sword and camp fire sfx could be bearable this way (and I wonder if these could also benefit from the random delay as the energy field has).

Not sure how to create a patch, but I did open a PR! [#485](https://github.com/exult/exult/pull/485). The values in there are very temporary but they do appear to work!

**Comment by rofl0r** [comment]
> Not sure how to create a patch

you squash your commits into one using git rebase -i, then use git format-patch

**Comment by NotStanley4330** [comment]
> > Not sure how to create a patch
> 
> you squash your commits into one using git rebase -i, then use git format-patch

Thank you!!!

**Comment by NotStanley4330** [comment]
Here is a patch @DominusExult 
[0001-Added-sfx-volume-functionality.patch](https://github.com/exult/exult/files/14923410/0001-Added-sfx-volume-functionality.patch)

**Comment by DominusExult** [comment]
Works great and I have some (or most) that need a lower volume.

However I'm wondering about stuff that has more shapes (like surf) or several same sources in one place (like water). Maybe these could use yet another section that sets "exclusity". So when the sfx is already playing not another *same* sfx gets played. This could reduce noise, I think.

Thoughts?

**Comment by KnightCaptainU7** [comment]
I'm under the impression that sound should work like light, closer is
louder/brighter. But turning on a bright light shouldn't automatically turn
off a lower output one.

**Comment by DominusExult** [comment]
I'm with you in regards to different sfx but in the case of surf, water it might make it less noisy and more pleasant on the ears

**Comment by NotStanley4330** [comment]
> Works great and I have some (or most) that need a lower volume.
> 
> However I'm wondering about stuff that has more shapes (like surf) or several same sources in one place (like water). Maybe these could use yet another section that sets "exclusity". So when the sfx is already playing not another _same_ sfx gets played. This could reduce noise, I think.
> 
> Thoughts?

I like this idea. I can try to add a flag for that. So if one is playing it checks to see if any of the same sound effect is playing and if it is listed as exclusive it won't. Might drastically change the soundscape of the game (but that probably wouldn't be a bad thing haha)

**Comment by KnightCaptainU7** [comment]
Would it be possible to have a setting with an in-engine graphical toggle
for this? That way exclusive sounds can be enabled or disabled?

**Comment by DominusExult** [comment]
If I understand you correctly, you'd rather have an option to disable shape dependent sfx?

**Comment by KnightCaptainU7** [comment]
Just the exclusive sounds setting, because I'm still not fully sold on the
idea but I don't want to be an impediment to any improvement.

**Comment by DominusExult** [comment]
right, sorry, misunderstood what your aim is. Not sure about a GUI for this (because it's just obscure and hard to explain) but an easy way to toggle this for advanced users is to just add a shape_info.txt to your patch folder (or to the mod's folder if you play one) in which you disable this for these sounds.

But right now I'm toying with several things to make the sfx easier on the ear.
