### ISSUE TITLE
FR: Zoom in Studio

### ISSUE THREAD

**Issue by KnightCaptainU7** [exult/exult#278]
Could you kindly add a zoom slider or drop-down in the lower right of the Exult Studio interface? It would make it easier to inspect things without changing system display settings.

**Comment by KnightCaptainU7** [comment]
Was digging into some older versions, with the older toolkit (GTK?) and found that seems to have a zoom level for shapes on by default.

![image](https://user-images.githubusercontent.com/117867844/202831314-0e295c8a-2e68-4ea1-a62f-1dcfaf583617.png)

**Comment by Dragon-Baroque** [comment]
Looking at the widgets in the menu bar, this looks indeed like an older GTK+.
But I migrated Studio to GTK+ 3 and I do not recall removing any zooming code from the Shape Browser.
For me to bissect the change, could you state the version and the date of the "Old Es", and possibly where you got it from ?

**Comment by DominusExult** [comment]
I couldn't find a version that did that but I only have a few scattered versions of the Windows build around (and none since before @Dragon-Baroque migrated Exult Studio). So @KnightCaptainU7 it would be really helpful if you can pinpoint date/version somehow.

**Comment by Dragon-Baroque** [comment]
I have rebuilt [ though on Linux ], Exult and Studio from the v1.6.x branch.
Studio from the v1.6.x branch _does_ show the older style widgets in the menu bar, but the Shapes have exactly the same size as in the master branch.

**Comment by DominusExult** [comment]
I tried builds as old as  from 2010 but as I said with a lot of gaps in between and all on Windows. (Tried different Windows versions, too).
Regardless, it would be a welcome addition to Exult Studio ;)

**Comment by Dragon-Baroque** [comment]
> Regardless, it would be a welcome addition to Exult Studio ;)

Agreed. I have made a simple test with `gdk_pixbuf_scale_simple` which is the solution proposed by your hint.
It is simple to code and it scales correctly, but then all size computations become wrong : the scrollers do not reach the bottom or the right, the selection rectangles are at the wrong place with the wrong size, and the selected shape is the wrong one.
And the only reasonable GDK Pixbuf scaler is the Bilinear. It works correctly for a scaling not above 200%. We could try to import the Exult scalers into Studio, but I doubt this would be worth the effort.

@KnightCaptainU7, @DominusExult, would you agree with a simple binary choice between : Zoom off vs Zoom on = 150%, like the _screenshot below using the GDK Pixbuf Scaler_ (  it looks like your screenshots above also use a 150% zoom ), and it would have minimal rounding error [ for shapes with odd width or height ].

Scaled 150% :
![Scaled150](https://user-images.githubusercontent.com/74261498/202924921-6dae1c2a-bf16-42dc-a760-b1f4b34a7805.png)

Original :
![Orginal](https://user-images.githubusercontent.com/74261498/202925547-803b09e1-9f9a-4a4a-a42a-e90560efcde5.png)

**Comment by marzojr** [comment]
Yeah, the size computations have to be redone for everything to work correctly; this includes the bounding boxes of selection and the scroller settings. They all need to be made aware of the current scale, and be invalidated/recomputed when scale changes.

I would argue against limiting to only 150% scale; with modern displays and resolutions, this can be very tiny still. Can you try to see what it looks like in your test when scaling using nearest neighbor by (say) 200% then bilinearly by another 150%?

**Comment by marzojr** [comment]
Also, for what is worth, as a _workaround_, the following environment variables can be used:

```bash
export GDK_SCALE=2        # Must be integer, scales everything by this factor
export GDK_DPI_SCALE=0.5  # Only for text, scales it by this factor
```
 Here is a comparison, both screenshots taken at the same monitor with maximized ES window:

Original:
![image](https://user-images.githubusercontent.com/4719275/202926854-5a5c4e9e-dba5-4045-825b-30e80ebc7dc8.png)
With the two variables above:
![image](https://user-images.githubusercontent.com/4719275/202926837-e26ba03c-2e01-41a7-bcc5-e1845a2e2ef2.png)

**Comment by Dragon-Baroque** [comment]
@marzojr :

A screenshot of a Nearest 200% followed by a Bilinear 150%, but my screen is only 1920*1080 :

![Scaled300](https://user-images.githubusercontent.com/74261498/202927143-7a25c2da-b959-416f-8a79-0bcf325c70c1.png)

Strange, can't get any effect with GDK_SCALE. GDK_DPI_SCALE=0.5 affects the text all right and the Shapes move because the GtkDrawingArea becomes a bit larger, but GDK_SCALE : no visible effect. Linux, KDE over Wayland, Studio uses GTK+ 3 at 3.24.34

**Comment by Dragon-Baroque** [comment]
And if you would like to test it, this is a very small patch into `Shape_draw::show` in `mapedit/shapedraw.cc` :
For your proposal of Nearest 200%, then Bilinear 150%, replace
```
gdk_cairo_set_source_pixbuf(drawgc, pixbuf, x, y);

```
by
```
GdkPixbuf *interm_pixbuf = gdk_pixbuf_scale_simple(pixbuf, w*2, h*2, GDK_INTERP_NEAREST);
GdkPixbuf *scaled_pixbuf = gdk_pixbuf_scale_simple(interm_pixbuf, w*3, h*3, GDK_INTERP_BILINEAR);
gdk_cairo_set_source_pixbuf(drawgc, scaled_pixbuf, x, y);
```
and add the `g_object_unref` of the temp pixbufs at the end.

**Comment by DominusExult** [comment]
Neither GDK_SCALE nor GDK_DPI_SCALE work on macOS https://discourse.gnome.org/t/how-to-disable-hidpi-on-macos-and-quartz-backend/1547/4

I'm gonna give the small patch a try.

A quick search on macOS and GDK_SCALE brought me to https://github.com/Beep6581/RawTherapee/issues/5291 - seems the proper way forward would be to abandon `Gtk::Pixbuf` for `Cairo::ImageSurface`

@KnightCaptainU7 the 
```
export GDK_SCALE=2        # Must be integer, scales everything by this factor
export GDK_DPI_SCALE=0.5  # Only for text, scales it by this factor
```
should work fine on Windows, give it a try.

**Comment by DominusExult** [comment]
@Dragon-Baroque the patch works as in your screenshot. It's pretty huge :) 
(and nothing works as you already commented).

**Comment by KnightCaptainU7** [comment]
The version in my screenshot is 2019-09-20, a 1.5.0 build. I have most of the installers for versions I have used.

@DominusExult where do I set those lines?

For simplicity's sake, could we do 2x, 4x, 8x? That way we keep the graphics as they are, without interpretation.

**Comment by DominusExult** [comment]
You set those in command line and start Exult Studio from that command line as well. Or you set them as global variable in Windows.
Honestly it's bern a while since I needed to do that in Windows, so I don't know how exactly you set the gobsl variables in (current) Windows anymore

**Comment by Dragon-Baroque** [comment]
@KnightCaptainU7, @DominusExult, @marzojr,

I have created a branch `studio-zoom-shapes` in my fork `Dragon-Baroque/exult`.
The commit provides Zooming of the Shapes in Exult Studio :

- The Zoom factor ( x1, x1.5, x2, x3, x4, x6, x8, x12, x16 ) and the Zoom mode ( Nearest or Bilinear ) can be set at the command line option `--zoom` or in a GUI in the menu bar, 
- The Zoom factor and mode are stored into and retrieved from the user configuration,
- The Zooming applies to the four Browsers ( Shapes and derivatives, Chunks, Npcs and Combos - when behind Exult ),
- The Zooming applies to the single Shapes in the Shape Editor and the other Editors ( Npc, Egg, Container )
- The Zooming applies to the Frame views in some pages of the Shape Editor ( Frame Names, ... ),
- The four Browsers react properly to a Zooming change [ Factor or Mode ].

Would you please evaluate and criticize...

**Comment by DominusExult** [comment]
make error:
```
npclst.cc:855:27: error: use of undeclared identifier 'newindex'
        chooser->scroll_vertical(newindex);
```

**Comment by Dragon-Baroque** [comment]
@DominusExult, sorry about that.
Fixed.
I compiled in DEBUG and this did not show.

**Comment by DominusExult** [comment]
Thank you! This works great and looks fantastic! Selecting, drag'n'drop into Exult all works fine.
Especially nice is that an Exult Studio window (like the shape inspector when you double click a file) also shows the zoom level and also update when you change the zoom level.
This is really great and don't want to live without it anymore :)

**Comment by Dragon-Baroque** [comment]
Thank you, @DominusExult, I appreciate that.

I intend to make some cleanup and then make a Pull Request.

Meanwhile, I have a few questions related to HiDPI :

1. What are _your_ screen size and dpi  ?
2. If it is High DPI, is there in macOS ( like it seems there is in Windows ) a way to claim that an application cannot see more than ( say ) 1920x1080 and the operating system scales the windows of the application up to the physical screen size ?
3. What is the resolution you use in **Exult** ( the default being 1024x768 ) ?
4. Could it be conceivable to provide **Exult** resolutions above 1200x900 ( this is the maximum resolution **Exult** proposes to me ) ? I would like 1280x800 ( 320x200 times 4 ) and 1280x960 ( 320x240 times 4 ). Is it because my screen is too small ( FullHD 1920x1080 at about 93 dpi ) that those are not proposed by Exult ?
5. When **Studio** is launched by **Exult**, would it be useful to propagate a Shape scaling _similar_ to the ratio Window Size by Game Area of the Video Options gump ? Than would propagate a 300% scaling when using the default 1024x768 Window Size above a normal 320x200 Game Area. I could take to caution step of checking the configuration Shape scaling and propagate a Shape scaling only if that is not set.
6. In **Studio**, the four browsers are paired : the Shape and NPC browsers have smooth vertical scrolling, the Combo and Chunk browsers always display shapes from the top - this is a vertical scrolling by entire rows of shapes. I understand that the Combo and Chunk browsers truncate to 128x128, but with a high shape scaling even that may not fit in the browser display and I cannot scroll down to the bottom of the Combo / Chunk. Would you prefer to unify the smooth vertical scrolling in the **four** browsers ?
7. By the way, when there is one row only in the Shape browser of Studio, by example on the ForgeOfVirtue with the Keyring mod, displaying the minimaps.vga, the same occurs when I scale the shapes up so that the minimap does not fit vertically, scrolling down to the bottom of the shape does not work. The scroller allows it but the minimap does not move. And sure I would like to look at the minimap in full with a large scaling. It this expected ?

**Comment by DominusExult** [comment]
1. 5120x2880 and 6400x2880 in hidpi, the ppi is 217.57
2. I don't think so
3. I really don't have a default size, it always depends on what I'm doing
4. see #105 - the windowed modes are hardcoded but if you enable fullscreen (without hitting apply, you should see the available modes) - maybe it would be a good way to set more default resolutions up to 5120x2880 (or higher), grab the maximum available fullscreen mode and cut the windowed modes off after the max available fullscreen mode. but that's another issue
5. I don't think that's really useful. I'd rather have Exult Studio remember the last used zoom
6. yes, I think smooth scrolling would be great on all
7. As you found the missing case my opinion is moot, but I would have said it's a bug :)

**Comment by Dragon-Baroque** [comment]
> 5120x2880 in hidpi, the ppi is 217.57.

That means 16:9, like my  1920x1080.
The hardcoded windowed resolutions split into a few multipliers of 320x200 [ 16:10 = original VGA ], and many more multipliers of 320x240 [ 4:3 = CRT ]. Exult does not hardcode any resolution for 16:9.

Should we organize the Video Gump by asking separately for the size ratio ( 4:3, 16:10 and 16:9 ), and propose Window Sizes that comply with the Size Ratio ? In my work for this Feature Request, I just tried to ensure that all resolutions exist both in 4:3 and 16:10 and to add a few resolutions up to 1920 ( thus my question about  _your_ resolution ), and the Window Sizes list is already quite large. Adding resolutions up to 5120 would make the list very large unless we remove all resolutions below 1024x768 or so.

Moreover, the display is _not_ stretched, that means it takes top and bottom black bands in 4:3 resolutions.
When you enforce 16:9 resolutions, you get left and right black bands instead.
I can understand the point of top and bottom black bands, that is where the Status Bar and Shortcut Bar go by default into.
But whereas the Status Bar can go into the left black bar, the Shortcut Bar remains on top. Should we consider allowing the Shortcut Bar to go to the right ? With 16:9 screens or wider becoming the rule, maybe we should consider exploiting the left and right black bars.

**Comment by DominusExult** [comment]
phew, I have no real idea what the correct thing to do here is. Mostly I think people don't know what ratio their screen is or don't care. Especially for the windowed view I don't think it really matters what ratio the screen has.
More modes for windowed mode are needed though, IMO.
Removing those below 1024x768 is reasonable anyways. At this time I doubt anyone running Exult windowed has a screen below that (though maybe some weird laptop resolution?). And special devices like iOS and Android run it in full screen anyways.

Shortcutbar on the sides would take some getting used to. but could be an option.

Maybe this discussion needs its own issue :)

**Comment by marzojr** [comment]
For what is worth, I am lately been using windowed mode at 962x900 window size and 3x scaling, with game area at 320x200 with aspect correction. I get black bars on top and bottom, but they are where shortcut bar and status bar go (mostly).

But I think that adding more resolutions would be useful. I think I like the idea about aspect ratio; instead of a list of resolutions, we can have a base aspect ratio and compute actual resolution based on game area, high dpi, aspect correction, and scaling factor.

And I also like the idea of allowing the shortcutbar on the sides for all the reasons you state.

**Comment by Dragon-Baroque** [comment]
> Shortcutbar on the sides would take some getting used to. but could be an option.
> And I also like the idea of allowing the shortcutbar on the sides for all the reasons you state.

I may have been wrong headed by proposing that, though. Looking at the code for the Status Bar when set Vertical, it uses the left black area for the first four members of the party, the right black area for the remaining four members. Am I wrong ?
Thus the right black area is already reserved.

> Maybe this discussion needs its own issue :)

Might be. Sure this is getting quite far from the scaling in Studio.

**Comment by Dragon-Baroque** [comment]
In Studio, I am working on the scaling of Chunks, trying to make the scrolling smoother.
Then I noticed that some Chunks in Studio look wrong. And different from Exult

 
![Untitled](https://user-images.githubusercontent.com/74261498/204656718-2190e808-0243-41f5-91ea-e8cd8639eb92.png)

This snapshot is from Studio at master, over Forge of Virtue, no mod.
The Chunk at about the center, with the mountain on the top left quarter and the coast on the three other quarters is number 65, and it displays a strange greenish horizontal line at the vertical middle, half right part.
Chunk 66 also shows a brownish horizontal line at about the same place, plus the bottom border looks like one pixel down with the right quarter.
Chunk 64 has three black inverted L and so has the Chunk above it, one of which at the bottom looks fully shifted one pixel down and right.

Do you see the same on your Studio ?

**Comment by KnightCaptainU7** [comment]
I'm using 3840 x 2160 (4K) with 150% scaling in Windows.
In Exult, I'm using 1680 x 1050 with x4 scaling, using the Point scaler. HighDPI is enabled, running in non-full-screen.

If you have a binary available I can test.

**Comment by DominusExult** [comment]
@KnightCaptainU7 https://www.dropbox.com/s/ch05q5t2lg0ncvz/ExultStudioZoom.exe?dl=0 <- Exult Studio with zoom

@Dragon-Baroque I see those lines everywhere (on macOS and Windows) but the chunks are fine in Exult. AFAICT this always looked like this in Exult Studio (tested a couple of years old version).
Another issue...

Shortcutbar to the sides: we probably need some logic that status bar and shortcut bar doesn't mix. So if shortcut bar is enabled, status bar cannot be enabled on the same spot. OR only if the the black bar is wide enough to allow two rows.

**Comment by Dragon-Baroque** [comment]
@DominusExult, @KnightCaptainU7, you need the `exult_studio.glade` too, to display the Shape Scaling widgets.

Otherwise the widgets won't display ( lack of anchor ), apparently Studio does not crash, but you can scale the Shapes only in command line :

Examples : `--zoom 400` or `--zoom N400` for Nearest 400%, `--zoom B150` for Bilinear 150%,
Syntax is `--zoom [B|N]number` B for Bilinear, N for Nearest (default), number is one of 100 (no scaling), 150, 200, 300, 400, 600, 800, 1200, 1600.
I can add more at the end if needed...

@KnightCaptainU7, On the other hand, if you have a text editor ( Notepad++, say ), this is a one line change of :
`<object class="GtkBox" id="hbox9">` to `<object class="GtkBox" id="menubar_box">`, to rename **hbox9** to **menubar_box**.

> Could you make the zoom function work with + and - keys?

Very nice. Certainly. You mean the notepad + and -, I suppose ?

**Comment by DominusExult** [comment]
The build I uploaded is a complete setup with all the files, including the glade file.

I have to test whether Exult makes adifference between notepad +/- and the other

**Comment by Dragon-Baroque** [comment]
> The build I uploaded is a complete setup with all the files, including the glade file.

Selbstverständlich. Apologies.

> I have to test whether Exult makes a difference between notepad +/- and the other.

I have added the + and Keypad +, - and Keypad - actions into my prototype.
I would prefer to let only the Keypad + or -, if only because I do not find quickly + or - ( on my keyboard one is shifted, not the other ), but I shall follow your advice. The four keys work at this point and do not interfere with the other uses of the keyboard.

> I see those lines everywhere (on macOS and Windows) but the chunks are fine in Exult.

Do the various tiles in a chunk have an height ? Then might this come from differences in height of the various tiles in a chunk, that Exult would respect but Studio would ignore ? That would explain the right and down shift...

Next step : a Pull Request, leaving aside the open issues ( the proposal for new resolutions in _Exult_, the strange chunks, and possibly the smooth scrolling of chunks and combos ).

**Comment by Dragon-Baroque** [comment]
Pull Request #281 contains :

- Some new resolutions in Exult,
- Zooming of Shapes, NPCs, Combos, Chunks,
- Setting Zooming by command line, GUI in menu bar, Keypad and Main + and -,
- Scrolling smoothly Shapes, NPCs, Combos and Chunks.

**Comment by Dragon-Baroque** [comment]
Pull Request #281 merged by @DominusExult, thanks.

Cosmetic follow up Pull Request #282 merged by me :
- Prevent unexpected vertical moves in the Combo browser and the Chunk browser when changing the Zooming scale.

**Comment by DominusExult** [comment]
@KnightCaptainU7 the new version of Exult and Studio are at https://github.com/exult/exult/releases
The automatic job that copies the snapshots to our regular download page failed for some reason :(

**Comment by Dragon-Baroque** [comment]
@KnightCaptainU7, @DominusExult, with the latest Pull Request #287, the present Feature Request should now be complete.
When it is snapshoted, would you please review it, so that we may close the issue.

**Comment by KnightCaptainU7** [comment]
From a quick look, it's amazing. Check out the "priestess" shape in SI and you can see the many color errors for example.

I cannot thank you enough for this!

**Comment by Dragon-Baroque** [comment]
One more Pull Request #290 to handle the Horizontal Scrollers and some forgotten changes in 84c8cc69 [ Frame mode in the NPC browser ].

Favorite Quote of the Computer Entomologist : `There is always one more bug`.

> Check out the "priestess" shape in SI and you can see the many color errors for example.

What is your point, please ?

**Comment by KnightCaptainU7** [comment]
My apologies, to clarify it shipped from Origin with a number of misplaced pixels, so it's a good use of zoom to see them.

**Comment by Dragon-Baroque** [comment]
May I consider the issue to be satisfied and close it ?

**Comment by DominusExult** [comment]
Yes!
