### ISSUE TITLE
U7-BG/SI: Poisonous enemies don't poison at all

### ISSUE THREAD

**Issue by zosite** [exult/exult#307]
Just like the title says: snakes and other enemies capable of poisonous attacks in the original games don't seem to be able to poison party characters. It's either that or I've been extremely lucky to date, for I haven't seen yet a single poisoned status coming from anything outside poisonous fields, poison potions, swamps and other hazards.

**Comment by marzojr** [comment]
I did some testing, and it seems that the root cause is that the root cause is here:
```c++
			const int attint = Get_effective_prop(npc, Actor::intelligence, 16);
			const int defstr = Get_effective_prop(this, Actor::strength);
			const int defint = Get_effective_prop(this, Actor::intelligence);

			// These rolls are borne from statistical analisys and are,
			// as far as I can tell, how the game works.
			if ((powers & Weapon_data::poison) && roll_to_win(attint, defstr)) {
				set_flag(Obj_flags::poisoned);
			}
```
I did some additional digging, and there is a correlation I had missed before: if the weapon does no damage whatsoever (like a spell), this code is correct; if the weapon does any damage, the attacker's intelligence plays no role and a 16 is used instead. This is critical for snakes, with their intelligence of 5...

This is not only for poison, but for all spell effects (paralyze, curse, charm, and sleep).

**Comment by DominusExult** [comment]
Another one we had wrong since forever 🤷‍♂️
Thanks for digging in
