### ISSUE TITLE
Can't sell flour to Willy the baker

### ISSUE THREAD

**Issue by AJRubenstein** [exult/exult#321]
Okay, so hear me out - I haven't played in ages, and I got suckered into the barter system of Willy the Baker. I know, rookie mistake. But I did notice that even if i have flour in my inventory, he tells me that I have no flour to sell him. Is this intentional or a bug? Latest SVN btw. Cheers!

**Comment by DominusExult** [comment]
I can confirm this.
Only if you have a sack of flour on you will Willi offer you the option to buy a sack of flour and then he will check how many and will not find any. Curios

**Comment by DominusExult** [comment]
Seems it is an undocumented usecode bug https://sourceforge.net/p/exult/bugs/1102/ @marzojr  :)

You only get the option to sell flour if
- you talked with Willie about hire
- you bought flour ("kitchen item") in paws (stealing flour in Paws did not make the "sell flour" option appear)
And then it fails.

**Comment by marzojr** [comment]
Wilhem's usecode is very buggy. Here is the gist of how the usecode goes:

1. Usecode looks if anyone in the party is carrying shape 863 frames 14 and 15. If any objects of either frame are present, "sell flour" is added to the list of dialog options.
2. When "sell flour" is selected, usecode counts how many objects of shape 863 frames 14 and 15 the party is carrying. If *either* count is zero, he thinks you don't have any to sell.
3. He buys the flour: he gives out all the gold, then removes all instances of shape 863 frames 14 and 15 in the party's possession.

Now, there are a few bugs here:

1. The closed flour shapes are frames 13 and 14, not frames 14 and 15. This bug is repeated 3 times in the usecode. Frame 15 is a butter churner, by the way.
2. If you are carrying 200 instances of frame 14 (a closed flour bag) and 0 instances of frame 15 (butter churner), you cannot sell any of your flour to him.
3. He pays you up before taking the flour. So this can cause you to miss out on your gold if you were overburdened before.

As an additional oddity, Wilhem divides the quantity of frame 15 by 1, then adds to the quantity of frame 14, before multiplying by the sell price.

**Comment by marzojr** [comment]
Oh, and he does not check for open sacks of flour at all. But this might have been intended.

**Comment by i30817** [comment]
BTW marzo, are you aware of the nitpick thread on the exult forums? I'm only asking because there are ... so many things there that are either bugs or could be part of si-fixes, and the thread is fairly recent.
https://exult.sourceforge.io/forum/viewtopic.php?f=1&t=1791299

**Comment by AJRubenstein** [comment]
> Seems it is an undocumented usecode bug https://sourceforge.net/p/exult/bugs/1102/ @marzojr :)
> 
> Apparently Marzo knows about this as he fixed it in the BG Keyring mod :) https://github.com/exult/exult/blob/master/content/bgkeyring/src/npcs/willy.uc#L36
> 
> hence I'm closing this issue.

huh, that's interesting. I'm using the Keyring mod and it's still doing it. Strange.

**Comment by marzojr** [comment]
I can sell with no problems using Keyring while carrying any combination of the 3 types of flour he takes. Can you provide a savegame?

**Comment by AJRubenstein** [comment]
> I can sell with no problems using Keyring while carrying any combination of the 3 types of flour he takes. Can you provide a savegame?

well. it would seem i started the game without the mod started. I feel a bit silly. Working now!
