### ISSUE TITLE
Mods failed to be detected

### ISSUE THREAD

**Issue by dagdha2002** [exult/exult#335]
Hey! First of all, thank for your work bringing Exult to Vita. I have an issue trying to play some Exult Mods. In the Vita they give me this message: Description missing! Wrong Exult Version. Thanks for your help.

**Comment by DominusExult** [comment]
Hi,
The vita port was not done by us, so we have no idea how that works in detecting the games and mods.
But generally the structure should be that in the game folder (eg blackgate) you should have the STATIC folder and the "mods" folder.
In the mods folder you extract the mod to. So the cfg file of the mod is in the mods folder and the mod in a subfolder.

**Comment by dagdha2002** [comment]
Ok, thanks for the answer. I´tried to let an issue in the github of the developer who made the Vita port, but I have to make a mistake somewhere. And yes, the structure of the mods folder is correct in my Vita. I´ll try to communicate with the developer. Thanks anyway for all the work in Exult.

**Comment by i30817** [comment]
Tell your port guy that if he wants to hardcode the path of the mods to another path, it's relatively easy to do it when using ./configure.

The important one for the game data is `--datadir=/usr/share/games` (in my case) and '--enable-mods'. The inbuilt mods (serpent isle fixes and blackgate keyring) are can be placed on the data dir to show automatically (without editing a config file for the user) with current git of exult. When i say 'can' i don't mean 'it's automatically done', the install package still needs to place them there.

That --datadir path can be anything else.

That directory will/should have a exult subdirectory with the game subdirs (blackgate and serpentisle), and those directories in turn have the static folders (for original game data) and the mods folders (with the mod data).

His installer/package should either instruct the user to place the 'normal' data on the right folder or force the user to provide a path for the copy (which is what i do in linux since i require root), and place automatically the game mod files that exult builds with (again, serpent isle fixes and blackgate keyring) on the right dir.

**Comment by marzojr** [comment]
> Maybe i'm doing it wrong and i was supposed to do
[snip]
> ```
> /usr/share/games/exult/blackgate/mods/
> ├── keyring
> └── keyring.cfg
> ```

This is what is intended; you are not doing it wrong. The cfg is there to tell Exult information about the mod, including where it is located: while the default is a directory of the same name on the directory as the cfg file, the cfg can override the directories and they don't need to be there at all.

For example, on my mods dir for FoV, I have a custom Keyring-ed.cfg that points to my Exult source tree (and similar for SI Fixes), so it is easier to edit the mods in ES.

**Comment by Dragon-Baroque** [comment]
I happen to have `Keyring/` and `Keyring.cfg` in `share/exult/forgeofvirtue/mods/`.
Forge of Virtue instead of Black Gate because that is where my Ultima VII Part 1 resides
And with upper case first letter `K`.

**Comment by i30817** [comment]
It's different in linux. Windows is case insensitive, linux is case sensitive. So if the case was different, the directory name would also have to be uppercase.

**Comment by i30817** [comment]
> > Maybe i'm doing it wrong and i was supposed to do
> 
> [snip]
> 
> > ```
> > /usr/share/games/exult/blackgate/mods/
> > ├── keyring
> > └── keyring.cfg
> > ```
> 
> This is what is intended; you are not doing it wrong. The cfg is there to tell Exult information about the mod, including where it is located: while the default is a directory of the same name on the directory as the cfg file, the cfg can override the directories and they don't need to be there at all.
> 
> For example, on my mods dir for FoV, I have a custom Keyring-ed.cfg that points to my Exult source tree (and similar for SI Fixes), so it is easier to edit the mods in ES.

Sure, but then it is a bit weird that the path in the source for the mod misguides people into thinking it's supposed to be 'bgkeyring' for the mod directory and 'keyring.cfg' (or rather 'Keyring.cfg') for the mod cfg file when that doesn't work then.

**Comment by i30817** [comment]
I also find it a bit weird we're supposed to copy all of the game into those folders according to the readme.

```
ls /usr/share/games/exult/blackgate/
 endgame.exe   install.pif   mainmenu.exe  'temp0003.$$$'   ultima7.com
 gamedat/      install.prm   mods/	    u7.cfg
 install.exe   intro.exe     static/	    u7.exe
```

I understand intro.exe and endgame.exe and static is obvious. But why the cfg, why the executables, why the tmp file etc. It's easier for me to just copy everything of course, but still putting executables in the root filesystem in linux is a bit of bad form.

**Comment by DominusExult** [comment]
We actually only need and make use of the files in the static folder. It's just not stated everywhere to make it an easy instruction.
No offense meant but just by stating "we only need the static folder, so point the cfg at the folder containing the static folder" adds complexity that makes people fail the instructions.

**Comment by i30817** [comment]
Only those? Not the gamedat?

**Comment by DominusExult** [comment]
No, gamedat just holds the original's current saved/loaded game and we don't read or use it

**Comment by i30817** [comment]
Gezz. I just update the package then.

**Comment by DominusExult** [comment]
I'll make a note to write something up for https://exult.sourceforge.io/docs.php#Installing%20the%20original%20Ultima%20VII%20games%20for%20use%20with%20Exult
