### ISSUE TITLE
CoreAudio on macOS try again without soundfont

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#347]
CoreAudio on macOS can work without a soundfont set in exult.cfg `<coreaudi_soundfont>`. But when it can't load that soundfont (or when that setting is empty) it will fail and the default FMOpl is being used.
It would be a good idea for the driver to not try loading a soundfont when the setting is empty and to try again without honoring the setting when it fails to load the soundfont.

CoreAudio on iOS needs a soundfont set in exult.cfg.

**Comment by Dragon-Baroque** [comment]
@DominusExult, I tried to solve a similar situation of a missing `<fluidsynth_soundfont>` with FluidSynth in Linux in commit 2ac62628.
This was possible because one can query FluidSynth for its _default_ soundfont, and then use that default soundfont for the Exult required soundfont. I wonder whether you can query CoreAudio for a _default_ soundfont.

Now, there is also the issue of the default soundfont _directory._ In Linux it is `/usr/share/soundfonts/` with some kind of shadow in `/usr/share/sounds/sf2`. On a reasonably installed FluidSynth with its regular soundfonts, you shall find `/usr/share/soundfonts/default.sf2` ( the FluidSynth default ) being a symbolic link to `/usr/share/soundfonts/FluidR3_GM.sf2`.

Is there an equivalent _default_ logic for soundfonts on macOS ? on iOS ? Is there a default soundfont directory ?

**Comment by DominusExult** [comment]
On macOS, when no soundfont is configured (which is the default for CoreAudio) it uses the system soundfont automatically gs_instruments.dls (AFAIK). There is no default soundfont folder.
So I think I figured this out with my last few commits.
When no soundfont is set or it can't find the set soundfont, Exult will skip the soundfont loading and just use the default CoreAudio (which uses gs_instruments.dls). And if the soundfont loading fails (wrong file format or whatever) CoreAudio will fail completely as it was deemed safer by someone who wrote that comment in our code.

However for iOS, I need to bundle gs_instruments.dls with Exult (and hardcoded it) as iOS does not ship with that (or it is not accessible by the sandboxed apps).

**Comment by DominusExult** [comment]
The stacking of FluidSynth soundfonts was something Marzo put in and he had at that time a great sounding setup. I think outside of Linux this is a nice feature as it works directly in Exult. I think it's not as easy to have a similar working setup on macOS and Windows as yours. Especially on Windows people already struggle setting up Munt as a midi device as Windows makes it harder and harder to do this (as I've read on Vogons).

I have not heard about setting up something you described for CoreAudio on macOS. A quick search does not give me anything. Apparently ages ago you could set a different DLS soundfont for Quicktime and thus possibly for CoreAudio but not anymore. All I can find is that apps need to bring the ability to use different soundfonts on their own. Just like Exult does.

I disagree on the Digitial Music being the default. FMOpl is the one we can rely on to work, the digital music still needs to be downloaded and installed correctly (the Windows installer now has the option to do that). But once these are setup they work on macOS and iOS (I bundle these for iOS). Though I would agree that maybe setting them as default and FMOpl as fall back.

**Comment by Dragon-Baroque** [comment]
> Though I would agree that maybe setting them as default and FMOpl as fall back.

It would be a nice deal. Thanks.
