### ISSUE TITLE
Narrowing conversion error in recent gccs

### ISSUE THREAD

**Issue by i30817** [exult/exult#37]
https://github.com/exult/exult/blob/c441af94991e044211fa34dff19ce0fec9c5a8b5/mapedit/chunklst.cc#L738

Seems to only occur in some platforms, arm64 particularly. Maybe char there is unsigned?
```
chunklst.cc: In constructor ‘Chunk_chooser::Chunk_chooser(Vga_file*, std::istream&, unsigned char*, int, int, Shape_group*)’:
chunklst.cc:740:24: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
  740 |                        };
      |                        ^
chunklst.cc:740:24: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
chunklst.cc:740:24: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
chunklst.cc:740:24: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
make[3]: *** [Makefile:669: chunklst.o] Error 1
```

**Comment by i30817** [comment]
I'm going to disable the build of exult studio on arm (well anything but i386 and amd64) in the ppa until this is tested there.

**Comment by marzojr** [comment]
I did a fix for this particular case; it seems that GCC does enable -Werror=narrowing on ARM by default, and this warning does not happen in this case for x86/amd64.

Instead of disabling the build, can you append `-Wno-error=narrowing` to the compile flags and post all the narrowing warnings printed? I am afraid these you list may be the tip of the iceberg...

**Comment by DominusExult** [comment]
@i30817 can you see if there are more issues like this?

**Comment by i30817** [comment]
You're going to have to wait until tomorrow, which is when the ppa is going to run again now that i enabled the arm64 build and put in the warning flag.

I made the mistake when creating the recipe originally of choosing a version number based on upstream commit + date and i'm now afraid of changing it.

**Comment by i30817** [comment]
Also btw @marzojr . Is the overflow really what you want here? Arm64 has unsigned chars, so without that hardening flag that causes the error, -1 would already turn into \xff. But i386/amd64 would still be -1, is the -1 guarded against where that array is used and is now not working because it's \xff?

**Comment by marzojr** [comment]
It is more complicated than that: it is possible to override these defaults with compiler flags (`-funsigned-char` or `-fsigned-char`), and some OSes may actually define (and enforce) different defaults for char sign. For example, on Android, gcc uses unsigned char even for x86/ia64.

Using `'\xff'` is the portable way to specify what is desired in this case: an 8-bit char with all bits set. Using -1 is actually wrong in this case if you were to ever compile on a platform where char is not 8 bits wide. Not that Exult would even compile there, but still...

**Comment by i30817** [comment]
Right, i think that was the last anyway. At least if the build logs mean anything:

arm64: https://launchpadlibrarian.net/475254593/buildlog_ubuntu-bionic-arm64.exult_1.5.0+svn20200419~ubuntu18.04.1_BUILDING.txt.gz

i386: https://launchpadlibrarian.net/475253212/buildlog_ubuntu-bionic-i386.exult_1.5.0+svn20200419~ubuntu18.04.1_BUILDING.txt.gz

amd64: https://launchpadlibrarian.net/475253184/buildlog_ubuntu-bionic-amd64.exult_1.5.0+svn20200419~ubuntu18.04.1_BUILDING.txt.gz

no 'narrowing' conversion warnings. A bunch of 'compassion always false', 'infinite loop detected' and something wrong on SDL2 that appears everywhere, a bunch of potential NP, and a warning about a macro that prevents reproducible builds. But no narrowing, even in the arm64 log.

**Comment by marzojr** [comment]
Thanks!

I will look into the 'comparison always false' warnings.

The 'infinite loop detected' warnings are from usecode in Keyring mod; I need to upgrade the loop detector in UCC so that it detects that the loops have a (provably) reachable exit, and they are harmless.

The SDL2 warnings can be worked around, but would be better off reported to SDL devs; especially the -Wundef warnings.

The warnings about potential null pointer dereferences are an embarrassment to compiler authors; a bunch of them are of the form `if (a && a->check())`, and the warning complains that a may be null inside `check`... which is clearly not possible unless the compiler is doing something seriously wrong.

The warning about reproducible builds are, unfortunately, unavoidable as we add in the date and time stamp at the time version.cc is built.

Anyway, this issue is technically closed, but I will wait to mark it as such until I deal with the  'comparison always false' warnings, which are related to this -- it also stems from a difference in signedness of char.

**Comment by i30817** [comment]
Have you considered adding instead the time and date of the last commit? That would make the build reproducible, though admittedly it would require a weird dependency on git.

**Comment by marzojr** [comment]
The remaining issues related to char sign have been fixed. I am setting this to closed. Thanks!
