### ISSUE TITLE
Exult Studio needs configure option --enable-exult-studio-support

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#393]
I just noticed something that needs fixing in configure.ac for Exult Studio's build (not only with SDL3).

I thought (wrong as it is now apparent) that in theory the configure flag `--enable-exult-studio-support` (-> `USE_EXULTSTUDIO` in config.h) should only matter for Exult not Exult Studio. But a lot of server stuff has `#ifdef USE_EXULTSTUDIO` and while Exult Studio builds without `--enable-exult-studio-support`, parts of it don't work correctly (like the server stuff - it will happily drop a shape in Exult but without the footprint, paint with..., doubleclicking a shape in Exult to open a ES window about it... <- all not working without server :)).

So in configure.ac the Exult Studio check should enable Exult studio support and come before the Exult Studio support check.
Or rather these two checks should be made one (?) and a failure of the Exult Studio support conditions should disable building Exult Studio altogether (or print out a warning that vital functions for connecting ES with Exult are not available).
Seems configure.ac could use a restructure there as well to consolidate all ES stuff in one section (gtk, gdk-pixbuf, icu, freetype, ES support, ES build).

**Comment by Dragon-Baroque** [comment]
I would like a single `--enable-exult-studio` option, dragging the present effect of `--enable-exult-studio-support`.

Now, if we keep its default to `no`, then I propose that any failure of the present checks for `--enable-exult-studio` or `--enable-exult-studio-support` cause a build abort. Because if I as a developer have explicitly requested Studio, I do not want Studio not to be built just because there is some missing third party component missing, like `gtk-devel`.

In terms of cleaning `configure.ac` up, I would also like :
- We remove the `m4/` folder and its outdated or unused macros, like I proposed for SDL 3.
- We remove the `acinclude.m4` and its `EXULT_CHECK_SDL` macro. As you said SDL 2 has entered maintenance mode in November 2022 at the time of 2.26. It is now at 2.28. We could replace the whole `EXULT_CHECK_SDL` by a requirement of SDL 2 at level 2.26.

Less important, but nagging me every time I look into `configure.ac` :
- Remove the `mingw32` stuff, as we now use `Makefile.mingw`,
- Shrink the list of compilers somewhat. I can assert than `xlC[_r]` has no place for Exult, because this compiler is for the IBM pSeries server under AIX - rack mount, server room -, and no system manager of such a beast would allow the installation of Exult or SDL on it.

**Comment by DominusExult** [comment]
I did the Exult Studio thing:
https://pastebin.com/y2RqUcYb
[configure.patch](https://github.com/exult/exult/files/12505789/configure.patch)

When you enable Exult Studio, support for it is enabled as well.
Checks for Gtk, Icu, Freetype are now only done when you enable Studio (and not android, maybe this could use another fine tuning: when enable Android, disable Studio, so these checks could be on Studio condition only).

Final printout of libs is also dependent on the Studio condition.

**Comment by DominusExult** [comment]
`We remove the acinclude.m4 and its EXULT_CHECK_SDL macro. As you said SDL 2 has entered maintenance mode in November 2022 at the time of 2.26. It is now at 2.28. We could replace the whole EXULT_CHECK_SDL by a requirement of SDL 2 at level 2.26.`
Hmm, setting it to 2.26 is rather high. We usually opt to keep the version requirement down as sometimes certain linux distributions really take their time to update to newer versions. If we set it to 2.0.14 we can get rid of some `#if SDL_VERSION_ATLEAST(2,0,14)` in the options gumps (I think these are the last places where we check for SDL Version).
`acinclude.m4` had been written when we ported from SDL 1.x to SDL2 and be able to switch between those in configure. Finally abandoning SDL 1.x with the release of Exult 1.6.
As we are likely not needing it anymore, it can go, I guess.

**Comment by DominusExult** [comment]
Asigning this to me for Milestone 1.10 - most has been done by now but macOS static linking can go

**Comment by DominusExult** [comment]
I think it's safe to remove the macOS X11 way.

As for requiring SDL +2.0.16, that depends on which SDL2 version the major distros use these days. I have no idea. But that's probably safe to assume. 2.0.14 was released July '21, 2.0.16 just a month later.

acinclude.m4 - I have no opinion on this ;)

**Comment by Dragon-Baroque** [comment]
> ..., that depends on which SDL2 version the major distros use these days.

Considering our build actions, I think that Ubuntu 22.04 LTS is our reference, until GitHub switches to the imminent 24.04 LTS. Ubuntu 22.04 LTS uses SDL 2 2.0.20, if I read the `ci-linux` action logs correctly, so 2.0.16 should be safe.

The macOS, freeBSD, OmniOS, MSVC and Windows builds find SDL 2 at 2.28 or 2.30. I cannot find the versions of SDL in the iOS and Android builds, perhaps you could tell me ?

Also I tend to recall a point, by Marzo perhaps, that Steam could lock us to an even older SDL.
Well, I am not sure, but I have downloaded the latest SteamOS and it uses SDL2 2.26.5.

> `acinclude.m4` - I have no opinion on this ;)

Sorry. I had not stated clearly in this thread that the SDL 3 branch had discarded the `acinclude.m4` because its `configure.ac` did not use the special `EXULT_CHECK_SDL` provided in it, and used a regular 
`PKG_CHECK_MODULES(SDL, sdl3, , AC_MSG_ERROR([[*** SDL not found!]]))` instead.

My question was about to do the same for SDL 2 in Exult 1.10, I mean remove `EXULT_SDL_CHECK` from `configure.ac` and replace it by a `PKG_CHECK_MODULES(SDL, sdl2 >= 2.0.16, , AC_MSG_ERROR([[*** SDL not found!]]))` and discard `acinclude.m4`.

**Comment by DominusExult** [comment]
> I cannot find the versions of SDL in the iOS and Android builds, perhaps you could tell me ?

Android is in `android/makefile.am` and iOS in `ios/Exult.xcodeproj/xcshareddata/xcschemes/git_clone_release_dependencies.xcscheme` - both at SDL2 2.28.2.
So upping our required version to SDL2 2.0.16 and removing the checks in the gumps is safe.

And yes, let's get rid of` acinclude.am`. Its existence was mostly due to the transition to SDL2 when we supported both versions.
Once the automatic checks pass, it's safe IMO for the 1.10 release.

**Comment by Dragon-Baroque** [comment]
This is PR #506.

**Comment by DominusExult** [comment]
Now it's truly closed :)
Thank you!
