### ISSUE TITLE
clang 17 and 16 warnings

### ISSUE THREAD

**Issue by nunotexbsd** [exult/exult#416]
I've noticed a lot of warnings on clang 17 and 16 that might upstream be interested in take a look.
Tested with 1.9.0.20231225 on FreeBSD.

```
2814 warnings generated.
mv -f .deps/paledit.Tpo .deps/paledit.Po
2802 warnings generated.
mv -f .deps/ucbrowse.Tpo .deps/ucbrowse.Po
2806 warnings generated.
mv -f .deps/shapegroup.Tpo .deps/shapegroup.Po
2810 warnings generated.
mv -f .deps/studio.Tpo .deps/studio.Po
2802 warnings generated.
mv -f .deps/shapefile.Tpo .deps/shapefile.Po
2810 warnings generated.
mv -f .deps/shapeedit.Tpo .deps/shapeedit.Po
2826 warnings generated.
```

clang17 [log](https://people.freebsd.org/~eduardo/logs/clang_warnings/exult-devel/15amd64_exult-devel-1.9.0.20231225%2C1.log) ~74MB
clang16 [log](https://people.freebsd.org/~eduardo/logs/clang_warnings/exult-devel/140amd64_exult-devel-1.9.0.20231225%2C1.log) ~71MB
clang14 [log](https://people.freebsd.org/~eduardo/logs/clang_warnings/exult-devel/132amd64_exult-devel-1.9.0.20231225%2C1.log) ~ 631KB

**Comment by Dragon-Baroque** [comment]
This is shortly mentioned in issue #394.

All GTK callbacks, whatever their true signature, are cast as `GCallback` or `(void)` ( without arguments ).
All these casts fail with the new warning `-Wcast-function-type-strict` from CLang 16, that is dragged by `-Wcast-function-type`.
Until we reach a decision, I suggest you alter `./configure.ac` by adding `-Wno-cast-function-type-strict` after `-Wcast-function-type`. 

Now if there remain other differences in CLang between 14, 16, and 17 that the `-Wcast-function-type-strict` warnings, we are interested.

**Comment by nunotexbsd** [comment]
@Dragon-Baroque 

I've follow your sugestion and logs back to normal. 

- affected clang 17,16 (with -Wno-cast-function-type-strict added)
- unaffected clang 15,14,13

exult 1.8 and 20231225 [logs](https://people.freebsd.org/~eduardo/logs/clang_warnings/exult-devel/Wno-cast-function-type-strict/)

Thanks!

**Comment by Dragon-Baroque** [comment]
@nunotexbsd 

Thank you for the logs as I can only test CLang 17. Except that I do not find the logs for CLang 15 ? Not very important, though...

Now, you get a recurrent warning at `SDL_events.h` line 676. Prossibly because `NULL` is defined as `0` by `SDL2/begin_code.h` whereas it should be defined as `__null` by `/usr/lib/clang/17/include/stddef.h` ( 17 replaced by the CLang version ).

Could it happen that your SDL `SDL2/SDL_config-x86_64.h` be different from mine : at around line 50 in it, I have this :
```
/* Comment this if you want to build without any C library requirements */
#define HAVE_LIBC 1
#if HAVE_LIBC

/* Useful headers */
#define STDC_HEADERS 1
```
with both `HAVE_LIBC` and `STDC_HEADERS` set to 1 ?
Actually, @DominusExult, could you too also look into your `SDL2/SDL_config-x86_64.h` ?

**Comment by nunotexbsd** [comment]
@Dragon-Baroque 

```
Name           : sdl2
Version        : 2.28.5
```
`SDL2/SDL_config.h`:

```
/* Comment this if you want to build without any C library requirements */
#define HAVE_LIBC 1
#if HAVE_LIBC

/* Useful headers */
#define STDC_HEADERS 1
```

**Comment by Dragon-Baroque** [comment]
@nunotexbsd, your build logs are very helpful.

Would you be able to rerun the builds ( I am mostly interested in Exult 1.9 - devel - builds, much less in Exult 1.8 builds ) after you have installed `fluidsynth` and `mt32emu` ( it may be called `munt` instead of `mt32emu` ) for MIDI synthesis ? No change to `configure.ac` for these packages is needed : their support by Exult is built by default provided they are found during `configure`.

Would you be able to build with gcc ( g++ ), all versions you can find, instead of clang ( clang++ ) ? Less important, though.

You would still have to keep the `-Wno-cast-function-type-strict` change to `configure.ac`.

**Comment by Dragon-Baroque** [comment]
> munt or mt32emu is not present into our ports tree.
> Only in rare cases we build ports with gcc since our base compiler is clang.
> We are using a global CFLAGS that it is applied based on FreeBSD versions that have clang >=16 on base.

Good points, thank you.

> Build [logs](https://people.freebsd.org/~eduardo/logs/clang_warnings/exult-devel/Wno-cast-function-type-strict/exult-devel_FLUIDSYNTH/) with fluidsynth

Thank you.

**Comment by marzojr** [comment]
A few notes:

* I can see these warnings compiling on Ubuntu 23.10 on WSL using the LLVM PPA for clang-18.

* The warnings of this kind:

  ```
  /usr/include/glib-2.0/glib/glib-autocleanups.h:47:1: warning: cast from 'void (*)(GAsyncQueue *)' (aka 'void (*)(_GAsyncQueue *)') to 'void (*)()' converts to incompatible function type [-Wcast-function-type-strict]
     47 | G_DEFINE_AUTOPTR_CLEANUP_FUNC(GAsyncQueue, g_async_queue_unref)
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/glib-2.0/glib/gmacros.h:1371:3: note: expanded from macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
   1371 |   _GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS(TypeName, TypeName, func)
        |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/glib-2.0/glib/gmacros.h:1359:47: note: expanded from macro '_GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS'
   1359 |     { g_list_free_full (*_l, (GDestroyNotify) (void(*)(void)) cleanup); }                                       \
        |                                               ^~~~~~~~~~~~~~~~~~~~~~~
  ```
  They are because glibc uses a GCC extension: in GCC, `void(*)()` is a "universal" function pointer which GCC understands can be cast to any other function pointer type. The proper (portable) way to do this in c++ would be something like this:
  
  ```c++
  template <typename To, typename From>
  To safe_pointer_cast(From pointer) {
	  static_assert(std::is_pointer<From>::value && std::is_pointer<To>::value && sizeof(From) == sizeof(To), "Pointer sizes do not match");
	  To output;
	  std::memcpy(static_cast<void*>(&output),
	              static_cast<void*>(&pointer),
	              sizeof(From*));
	  return output;
  }
  ```
  
  A similar idea works for c, but you don't have a sane way to verify at compile time (without using the preprocessor) that the static assert works. Without such a function (using memcpy), or the GCC extension, the function pointer casts are, strictly speaking, undefined behavior -- which will work because of requirements imposed on pointers and function pointers by either POSIX or Windows (and because a function with the proper signature is being used for each case).

* Some other cases of -Wcast-function-type-strict are due to use of reinterpret_cast for the same purpose as above.

I pushed a commit that should fix all but the SDL ones.

**Comment by Dragon-Baroque** [comment]
@nunotexbsd, the latest snapshots should be completely warning silent on your FreeBSD builds.

Can we close the issue ?

**Comment by nunotexbsd** [comment]
@Dragon-Baroque 

Yes, I will close it now.

Everything is ok and port is at 1.9.0.20240105.
Clean logs (without any -Wno...)

Thanks!

**Comment by Dragon-Baroque** [comment]
@nunotexbsd, I wish to inform you that `autoconf-archive` is now a prerequisite for exult-devel on FreeBSD.
