### ISSUE TITLE
How to Git Rebase after clang-format

### ISSUE THREAD

**Issue by Dragon-Baroque** [exult/exult#422]
I have two work branches of Exult, one is for SDL 3 ( Exult ), one is for GTK 4 ( Studio ).

I have kept them in sync with master, using `git rebase`, but I get now a massive set of conflicts since the commit 83fac49ba.
The SDL 3 branch has about twenty commits, the GTK 4 branch has five, way bigger. I would like to keep all of them since they hold my history. Thus I think that I should have to fix all these conflicts for each commit of mine, although perhaps `git rerere` might just help.

I thought that it would be easier to apply to each single commit of my two branches the `clang-format` based on the `.clang-format` of the commit 83fac49ba, and then rebase to 83fac49ba.
Unfortunately, `clang-format` does not give me the same changes as 83fac49ba contains.
Indeed, if I checkout to the commit 8e2580137 just prior to 83fac49ba, import all the .clang* from 83fac49ba and apply clang-format to it, I get different changes from 83fac49ba, some missing blank lines, some comments indented to current code instead of not indented, the format of functions parentheses to parameters and opening braces being cut differently, ... When I apply `clang-format` a second time, or when I apply `clang_format` again to 83fac49ba, it does not make any further change, however.

@marzojr, do you remember whether the commit 83fac49ba is only a run of `clang-format` over `.clang-format`, or whether the commit contains _more_ changes, like hand edition, `clang-tidy` or anything ?
If it contains only a run of `clang_format`, could you post its version, and the result of `clang-format --dump-config`, which looks like an overset of `.clang-format`, while at the root of the Git tree of Exult, where `.clang-format` resides ?

**Comment by marzojr** [comment]
There was some minor editing, but mostly around the header area so they would be properly re-sorted. There were a handful of other code edits:
1. one place where there was an `#ifdef` block cutting through normal control flow;
2. a few places where headers were being included in the middle of the file, and a standard macro was being defined.

I doubt that any of these are causing the issues you are seeing. Other than those changes, it was just a straight apply of `clang-format`. But note that [83fac49](https://github.com/exult/exult/commit/83fac49ba434f09aceef2da438ac5f0fa69d35c0) also changed `.clang-format`.

I can try taking a look over the weekend; I think I have a few ideas on how to ease the process which I want to try out and see how well it works.

**Comment by DominusExult** [comment]
Once you sort it out, I propose you add those as branches to main Exult ;)

**Comment by Dragon-Baroque** [comment]
> Once you sort it out, I propose you add those as branches to main Exult ;)

About the SDL 3 branch, it was my intention as a gift to the project, although, as you know, it prereqs changes to SDL itself.
About the GTK 4 branch, it is stalled until 1- you confirm that the Drag and Drop of GTK 4 works on macOS [ the gtk4-demo ] test, 2- I complete the migration due to the massive set of deprecated objects that came in 4.10. So many things to do, so little time, you know that...

**Comment by Dragon-Baroque** [comment]
> I doubt that any of these are causing the issues you are seeing.
I agree.

> Other than those changes, it was just a straight apply of `clang-format`. But note that 83fac49ba also changed `.clang-format`.
I took the step of `git checkout 83fac49ba .clang*` to all these tests, including the test on the commit preceding it.

Could you return the result of `clang-format --version` ( I am at 17.0.6 ), and post here the result of `clang-format --dump-config` while at the root of the Exult Git tree ?

**Comment by marzojr** [comment]
```
$ pwd
/home/Marzo/exult
$ clang-format --version
clang-format version 17.0.6
$ clang-format --dump-config > clang-format-dump.txt
```
The result of that last command: [clang-format-dump.txt](https://github.com/exult/exult/files/13809226/clang-format-dump.txt)

(note that the above was executed on msys2 in Windows, as was the reformat)

**Comment by Dragon-Baroque** [comment]
> The result of that last command: [clang-format-dump.txt](https://github.com/exult/exult/files/13809226/clang-format-dump.txt)

Is identical to mine. Unfortunately ...

**Comment by marzojr** [comment]
Out of curiosity, are those branches of yours public? I am seeing only your SDL3 branch right now.

**Comment by Dragon-Baroque** [comment]
> Out of curiosity, are those branches of yours public? I am seeing only your SDL3 branch right now.

The SDL 3 branch on Dragon-Baroque/exult is very much older than on my fork at home : It expects a major rework of the Drag and Drop in SDL 3, and it is rebased at the commit **_prior to_** 83fac49ba. If playing with it may help you devise a strategy for us to rebase to master, I may update it.

The GTK 4 is not on Dragon-Baroque/exult even at home, it resides on a separate private git clone of Exult. I don't think it is publishable.

**Comment by marzojr** [comment]
> The SDL 3 branch on Dragon-Baroque/exult is very much older than on my fork at home : It expects a major rework of the Drag and Drop in SDL 3, and it is rebased at the commit **_prior to_** [83fac49](https://github.com/exult/exult/commit/83fac49ba434f09aceef2da438ac5f0fa69d35c0). If playing with it may help you devise a strategy for us to rebase to master, I may update it.

Ah, yes, please 🙂

**Comment by Dragon-Baroque** [comment]
Dragon-Baroque/exult branch exult-sdl3 refreshed.

Now please, @DominusExult, do not ever dream of trying it until I publish the SDL 3 patches.

**Comment by DominusExult** [comment]
> **Too Strong, Replacement** : @DominusExult, you could try it against a recent Git SDL 3. Exult should compile, and its video and audio should work. The Drag and Drop from Studio will not, if course. until I publish the SDL 3 patches.

I may have time tomorrow and will test and report back in the SDL3 issue.

**Comment by Dragon-Baroque** [comment]
> I doubt that any of these are causing the issues you are seeing. 

I am trying to rebase my GTK 4 branch at home, on commit at a time. In fact, I am getting convinced that those _other changes_ are precisely what is making my effort hard. Are you able to pinpoint them a bit more precisely ? And could you tell whether they were applied before or after the clang-format ?

Should you consider this kind of large change again, I would suggest that you make one commit of the editing changes that came prior to the clang-format, one commit for the clang-format strictly alone, one commit for the editing changes that came after the clang-format. This would simplify the rebasing effort considerably...

**Comment by marzojr** [comment]
I think that this may be another issue. Out of curiosity, what happens when you run that python script I gave you on a clean version of Exult master branch?

**Comment by Dragon-Baroque** [comment]
> Out of curiosity, what happens when you run that python script I gave you on a clean version of Exult master branch?

Since your latest commit 4f0e46752 of one hour ago : no change.

**Comment by marzojr** [comment]
I found a workflow. It has many conflicts to resolve, but they are due to the fact that the parents are being reformatted (more information below). I *think* I got everything right.

[Here are the results](https://github.com/marzojr/exult-dragon-baroque):
- branch [new-format](https://github.com/marzojr/exult-dragon-baroque/tree/new-format) splits [83fac49](https://github.com/exult/exult/commit/83fac49ba434f09aceef2da438ac5f0fa69d35c0) into 3 commits (one for updating `.clang-format`, one for reformat, one for fixups) then cherry-picks all commits from master after the reformat. You can use this as a base for the GTK4 branch.
- branch [exult-sdl3-rebase-work](https://github.com/marzojr/exult-dragon-baroque/tree/exult-sdl3-rebase-work) was created from the tip of [exult-sdl3](https://github.com/marzojr/exult-dragon-baroque/tree/exult-sdl3) and rebased onto [new-format](https://github.com/marzojr/exult-dragon-baroque/tree/new-format) splits [83fac49](https://github.com/exult/exult/commit/83fac49ba434f09aceef2da438ac5f0fa69d35c0). More details below.
- branch [exult-sdl3-reformat](https://github.com/marzojr/exult-dragon-baroque/tree/exult-sdl3-reformat) was created from the tip of master, then all commits from [exult-sdl3-rebase-work](https://github.com/marzojr/exult-dragon-baroque/tree/exult-sdl3-rebase-work) were cherry-picked onto it (so that they are now, essentially, on master).

The workflow:
1. setup the branches as described
2. rebase with this command (which is probably overkill):
    ```bash
    git rebase -Xignore-all-space --exec \
            'clang-format -i -style=file $(git diff HEAD~1..HEAD --name-only --diff-filter=ACMRT | \
            grep -E "\.(cpp|cxx|c++|cc|cp|c|i|ii|h|h++|hpp|hxx|hh|inl|inc|ipp|ixx|m|mm|txx|tpp|tcc|tpl)$") || \
            true ; git commit -a --amend --no-edit' new-format
    ```
3. resolve conflicts in VSCode (usually, clicking 'accept combination' then check diff versus original diff, sometimes more work is required).
4. Reformat all files (just in case) with command
    ```bash
    clang-format -i -style=file $(git diff --cached HEAD~1 --name-only --diff-filter=ACMRT | \
            grep -E "\.(cpp|cxx|c++|cc|cp|c|i|ii|h|h++|hpp|hxx|hh|inl|inc|ipp|ixx|m|mm|txx|tpp|tcc|tpl)$")
    ```
5. Make the commit and continue rebase
6. Repeat until the end

It was not pleasant, but manageable. The vast majority of the conflicts fell into the following categories:
1. caused by header reordering.
2. formatting (whitespace) changes between the "master" code and the incoming commit.
3. formatting (usually braces) changes between the "master" code and the incoming commit.
4. formatting changes between the the previous reformatted commit and the incoming commit.

All of these would also have happened if the reformatting commit had not split; and to test that, I compared merging the first of your commits into new branches created from [new-format](https://github.com/marzojr/exult-dragon-baroque/tree/new-format) and master, and compare the conflicts.

I am not sure how it would have gone if I had rebased on each of the reformat commits first, then rebased onto the tiip of master.

**Comment by Dragon-Baroque** [comment]
I was asking about a split 83fac49ba because I thought about the following workflow :

1. Rebase my branch normally, but up to the commit prior to the execution of clang-format,
2. In my branch, one commit at a time, from the root to the tip, do

- apply clang-format ( several times, until it stabilizes, I discovered that yesterday ), 
- then rebase to the commit of the execution of clang-format, **with the option -Xours**, telling it that all conflicts are resolved in favor of my commit - this should be OK, since my commit contains the clang-format plus my changes. Well I must admit that this is clear for the first commit of my branch, less so for the commits behind the first. Perhaps I should rebase them to their clang-formated and rebased parent instead. Or try some diff of the current commit after clang-format to its rebase and reformated parent.

3. Rebase my branch up to master.

I expected that you could place the _fixup_ commit _before_ the clang-format. It looks however as if you could not convince clang-format to do your mind, thus you had at least some changes _after_ the clang-format, that clang-format respected afterwards.
Thus the _fixup_ commit is rather large and could induce conflicts.

About the includes, is this order the desired one ?

- First, only in a `"<source>.cpp/.cc"` file, a master include of the name `"<source>.h"`,
- Then all required includes of Exult and dependent products, with double quotes, sorted by name,
- Then all required system includes, with angle brackets,
- Then all `using std::`.

Anyway, thank you, I now have to exploit your effort.

**Comment by marzojr** [comment]
>     * First, only in a `"<source>.cpp/.cc"` file, a master include of the name `"<source>.h"`,
>     * Then all required includes of Exult and dependent products, with double quotes, sorted by name,
>     * Then all required system includes, with angle brackets, also sorted by name,
>     * Then all `using std::`, also sorted by name.

Almost:
* First, the `config.h` include (if used);
* Then the `pent_include.h` include (if used);
* Then, in a `"<source>.cpp/.cc"` file, a master include of the name `"<source>.h"`,
* Then all required includes with double quotes, sorted by name;
* Then all required non-Boost includes with angle brackets with extension, sorted by name;
* Then the `mmsystem.h` include (if used), since it must come after `<windows.h>` include;
* Then all required Boost includes, sorted by name;
* Then all required standard library includes (angle brackets, no extension), sorted by name;
* Then all `using *`, also sorted by name (currently, mostly `using std::`).

`#ifdef` blocks tend to muck up this, as they prevent `clang-format` from reordering them.

**Comment by Dragon-Baroque** [comment]
@marzojr, With your help, my SDL 3 branch _and my GTK4 branch_ are now reformatted, rebased and track the changes on master.

You may discard the special fork you made over mine.

I am closing the issue.
