### ISSUE TITLE
Instant gamma shift bug on blackgate keyring mod

### ISSUE THREAD

**Issue by i30817** [exult/exult#43]
If you start keyring mod, then in the intro when Iolo and Petre are babbling press esc and go to video settings you get a abrupt transition to twilight and if you press esc you'll see the gradual morning.

The menus are also affected by the gamma shift, which is kind of bad i suppose, when you want to set a option in a dark cave.

I assume the game starts at morning-twilight time and the video code makes a executive decision to fix things. It doesn't happen in normal u7 for some reason.

**Comment by marzojr** [comment]
This is not specific to Keyring, it also happens without the mod. Also, the same thing might happen in original U7 if you could do anything in that first scene; the time the game starts at should be in twilight with dawn transition, but the game hardcodes it to day palette. I suppose that we could special-case the first day to only ever show day palette before 7 AM and it would fix this.

The menus being affected by palette is a separate issue. It is unfortunately, unavoidable due to the palletted nature of the graphics; fixing it would require a major overhaul of the graphics system.

**Comment by marzojr** [comment]
I have to correct myself; seems like Keyring's starting time is incorrect.
