### ISSUE TITLE
Studio crashes when exporting 

### ISSUE THREAD

**Issue by KnightCaptainU7** [exult/exult#447]
Latest snapshot and a build from late September have the same issue where ES crashes when trying to Export All Frames of a given Shape.

Here are error logs from the snapshot:
[studio_out.txt](https://github.com/exult/exult/files/14227464/studio_out.txt)
[studio_err.txt](https://github.com/exult/exult/files/14227465/studio_err.txt)

Both appear to show a mixing of Windows paths with backslashes \ and then a forwardslash is mixed in at Adwaita\scalable/status
`
(exult_studio.exe:1524): Gtk-WARNING **: 20:47:19.503: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk+-3.24.39/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load C:\Program Files (x86)\Exult-2024-02-09\share\icons\Adwaita\scalable/status\image-missing.svg: Unable to load image-loading module: C:\Program Files (x86)\Exult-2024-02-09\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll: 'C:\Program Files (x86)\Exult-2024-02-09\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll': The specified module could not be found. (gdk-pixbuf-error-quark, 5)
`

Both files exist:
C:\Program Files (x86)\Exult-2024-02-09\share\icons\Adwaita\scalable\status\image-missing.svg
C:\Program Files (x86)\Exult-2024-02-09\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll

Steps to reproduce:
Open Exult Studio.
Select Game and Mod.
Go to Shapes, right-click a shape, choose Export All Frames.
The new window for saving opens fine, but if you click on any option on the left or in the path buttons above the file list, crash.

Earlier I tried to Export All Frames, but that path defaulted to one inside Program Files x86. There I was able to make a folder, but I could not find that folder at the expected path using Windows Explorer. I was also able to save all of the images according to the GUI but I can't find the folder or files. I could go back into ES and see the folder, but it seems to be gone now. I think we should set the default export path to someplace known-writable like Documents\Exult.

**Comment by DominusExult** [comment]
@Dragon-Baroque any idea what is happening there? I cannot reproduce with native macOS Exult Studio but it happens with Windows Exult Studio via Wine.

> Earlier I tried to Export All Frames, but that path defaulted to one inside Program Files x86. There I was able to make a folder, but I could not find that folder at the expected path using Windows Explorer. I was also able to save all of the images according to the GUI but I can't find the folder or files. I could go back into ES and see the folder, but it seems to be gone now. I think we should set the default export path to someplace known-writable like Documents\Exult.

Newer Windows versions do some folder virtualization when you try to write to the "Program Files" folders. The folder is duplicates somewhere in your user profile and the file you saved should be found in there.

**Comment by Dragon-Baroque** [comment]
I tried on a Windows 10 up to date in VirtualBox, installed the latest 1.9 Exult.exe, ExultTools.exe, ExultStudio.exe from `exult.info` into the default path `C:\Program Files (x86)\Exult`, copied over my standard folders `forgeofvirtue` and `silverseed` and ran Studio against The Black Gate - Forge Of Virtue with and without the Keyring mod.

I Exported all frames from the Wood Roof, shape 176, into the default path, provided `test` as the root name, produced 5 PNGs in both cases, one case in `C:\Program Files (x86)\Exult\forgeofvirtue\mods\Keyring\data`, one case in `C:\Program Files (x86)\Exult\forgeofvirtue\patch\`. Neither the command line `dir` nor the Windows Explorer would list these two folders or their contents because they were actually in `C:\Users\<MyUser>\AppData\Local\VirtualStore\Program Files (x86)\Exult` because `<MyUser>` is not Administrator.

What is worrying in the issue is not only that GTK+ complained and crashed ( the Gtk:ERROR ) about not finding the `image-missing.svg`, but also that it actually attempted to use it, which means that it could not find **either** the image Studio wanted it to display ( the Gtk:WARNING just above ). I did not get any message from Gtk, warning or error.

**Comment by marzojr** [comment]
Maybe when Windows set up the virtualized path it caused GTK to fail because it was mistakenly looking there for the images?

**Comment by Dragon-Baroque** [comment]
As far as I know, the VirtualStore mechanism is a write access alternate to forbidden folders.
When the program searches or open-read a file, Windows searches for it in both the VirtualStore _and_ the regular folder, in that order.
Which means that the VirtualStore of Exult _could_ be polluted by some set of old files, that the Installer ( running Administrator ), the dir command or the Windows Explorer would not notice, but that Exult would unexpectedly bring in instead of the ones it want.

Which makes quite interesting the reproducible case by Dominus on Wine. Wine does not seem to emulate the VirtualStore.

**Comment by wench** [comment]
No idea what is going on here but it seems like it would be a good idea if Exult studio would refuse to edit games installed into program files or other read only locations. First step would be to add an appropriate manifest to ExultStudio to disable using the Virtual Store then calls attempting to write to program files will fail allowing easy testing of opening a read only game

**Comment by Dragon-Baroque** [comment]
I actually wonder why the Installer offers `C:\Program Files (x86)\Exult` as the default installation path instead of the `C:\Ultima7` default of `Makefile.mingw`.

**Comment by Dragon-Baroque** [comment]
Tried on Windows 11 VirtualBox. Same as Windows 10.

**Comment by Dragon-Baroque** [comment]
Some progress :

- I could reproduce the crash : Windows 10, Install Exult and Studio out of `C:\Ultima7` - for example the installation default `C:\Program Files (x86)\Exult`, ensure that at least one valid game is installed,
- ( From KnightCaptainU7 ) Open Studio, choose a game, select the `shapes.vga`, choose the `Wood Roof` shape 176, right click, `Export All Frames`, get the window `Choose the base .png file name for all frames`, click on one left icon - not all crash, but I could crash at all times with `Windows 10 (C:)`.

And there are indeed two issues :

1. When Exult and Studio are installed out of the U7PATH ( `C:\Ultima7` ), the File Chooser of GTK+ seems to miss one icon, and uses the `image-missing` icon to replace it,
2. The `image-missing` icon resolves into `scalable/status/image-missing.svg`, which is an SVG, its loader 
`gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll` is present but not loadable because it misses one dependent DLL `librsvg-2-2.dll`, which in turn misses two dependent DLLs `libxml2-2.dll` and `liblzma-5.dll`.

I struggled a while until I realized that the Exult + Studio snapshots are 32 bit builds, but when I copied the three DLLs from my MinGW installation into the installation folder of Exult along with the other dependent DLLs like `libglib-2.0-0.dll`, the crash ceased, and I did not get any GTK+/GLib warning anymore.

Considering that ExultStudio brings the Adwaita icon theme which is mainly made of SVGs, could we ensure that the **three dependent DLLs** of `libpixbufloader-svg.dll` ( `librsvg-2-2.dll`, `libxml2-2.dll` and `liblzma-5.dll` ) be shipped in the 1.9.0 snapshots of ExultStudio ?

As to why this does not occur when Exult + Studio are installed into `C:\Ultima7`, I cannot say...

**Comment by DominusExult** [comment]
Thanks for your debug. For some reason
```
define copy_dlls_for_exe
	for ff in $$($(MSYSTEM_PREFIX)/bin/ntldd -R $(1) | tr '\\' '/' | grep -io '[A-Za-z]:/.*$(MSYSTEM_PREFIX)/.\+\.dll' | sort -u); do cp $$ff $(2)/$$(basename $$ff); done
endef
```
fails in makefile.mingw.

> I actually wonder why the Installer offers C:\Program Files (x86)\Exult as the default installation path instead of the C:\Ultima7 default of Makefile.mingw.

C:\Program Files (x86)\ is the default for installing programs on Windows and should be followed. C:\Ultima7 in makefile.mingw should be considered a developers' thing only.

**Comment by KnightCaptainU7** [comment]
Agreed regarding Program Files.

The default path for saving on Windows generally is the current user's
Documents folder. Can we set that as ES default to avoid the current
default of trying to save inside of Program Files?

Thanks all for looking into these bugs.

**Comment by DominusExult** [comment]
> Can we set that as ES default to avoid the current default of trying to save inside of Program Files?

That would make sense IMO

Using `$$($(MSYSTEM_PREFIX)/bin/ntldd -R` in makefile.mingw fails as these dlls are not in the dependencies of exult_studio.exe.
So either we hardcode these three dlls or we need another `ntldd -R` for each of the libs in `path/lib/gdk-pixbuf-2.0/2.10.0/loaders/`

**Comment by DominusExult** [comment]
For now I hardcoded the three dlls to be installed in makefile.mingw. I used a wildcard for each to make sure future releases of the dlls that might change the name slightly are covered, too.

**Comment by wench** [comment]
Trying to save into Program Files is probably because that is the Current Directory. We should do a chdir somewhere to get out of the application's start up directory

**Comment by marzojr** [comment]
> Using `$$($(MSYSTEM_PREFIX)/bin/ntldd -R` in makefile.mingw fails as these dlls are not in the dependencies of exult_studio.exe. 

More specifically, `ntldd` fails because these files are loaded completely dynamically: their only references are in `$MSYSTEM_PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache`, a text file generated by `gdk-pixbuf-query-loaders`. Dominus' patch should also be failing because the files are being copied from the wrong location, the DLLs are in `$MSYSTEM_PREFIX/bin` not in `$MSYSTEM_PREFIX`.

**Comment by DominusExult** [comment]
Thanks for fixing this!

**Comment by KnightCaptainU7** [comment]
No more crash on exporting with the nightly build from the 22nd. When saving to an unwriteable location a message now appears saying permission denied.
