### ISSUE TITLE
1.9 snaphot compile failure maybe due to 'Getting rid of array_size' commit? Does exult now require a very recent version of c++ compiler?

### ISSUE THREAD

**Issue by psavola** [exult/exult#482]
The compilation of current snapshot taken from github fails on my Centos 8 stream as follows:

actions.cc: In constructor ‘Sequence_actor_action::Sequence_actor_action(Actor_action*, Actor_action*, Actor_action*, Actor_action*)’:
actions.cc:806:31: error: expected primary-expression before ‘]’ token
  actions = new Actor_action* [] {
                                                ^
actions.cc:808:2: error: too many initializers for ‘Actor_action* [1]’
  };
  ^

This is likely related marzojr's January commit of adding c++-20 compatible changes throughout the code:

https://github.com/exult/exult/commit/00da16d6fca391243a64dbd92ed8800758e7853c

I wonder if my gcc supports these:

$ g++ --version
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-21)
Copyright (C) 2018 Free Software Foundation, Inc.

If the compilation currently intentionally requires a very recent c++ version, at the very least this should be checked in configure stage? Or if this dependency is not intended, maybe this should be reconsidered or multiple versions supported? 

@marzojr

**Comment by Dragon-Baroque** [comment]
This could be only the trailing comma in the initializers list of `actions` in `actions.cc` line 806.
Could you try to replace 
```
               a0, a1, a2, a3, nullptr,
```
by
```
               a0, a1, a2, a3, nullptr
```
and rebuild ?

**Comment by wench** [comment]
That version of GCC is too old. according to this page https://en.cppreference.com/w/cpp/20 gcc only got array size deduction in new expressions in Version 11. Strange that gcc didn't support it in an earlier version.

GCC 8.5 just does not have full C++20 support

**Comment by marzojr** [comment]
Note that the changes, by themselves, use no c++20 functionality; they just add a span compatible with c++20's std::span because it is a really useful data structure.

In theory, GCC 8.5 should be enough for *this particular thing* because it claims support for all c++17 language changes by version 7 ([ref](https://en.cppreference.com/w/cpp/compiler_support/17) -- note *language features*, not *library changes*).

But in any case, GCC 8.5 does not have full c++17 support either (that is not come until GCC 12).

I don't see how we can portably require specific compiler versions; we just query if it supports c++17 support. The issue here is that the compiler is lying because it does not. And I really don't want to hard-code specific versions.

But as Alexis said, version 8.5 is far too old.

**Comment by wench** [comment]
except you changed a `new Actor_action*[5]` into `new Actor_action*[]` which is a c++20 only feature

**Comment by marzojr** [comment]
Oh, I see the issue.

![image](https://github.com/exult/exult/assets/4719275/f5b64454-7355-4f73-a672-c428182d06e0)

Deducing the size of an array in a new expression is a c++20 feature... that was applied as a defect report retroactively all the way back to c++11. GCC11 properly supports the feature on all modes, but older versions do not.

Yeah, putting the 5 back will fix the issue.

**Comment by psavola** [comment]
Confirmed that by adding '5' the compilation finishes fine.
