### ISSUE TITLE
Main menu fps setting always shows 5fps

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#488]
Even after setting it to 8fps (or any other), after restart the main menu will show 5fps but when you start a game it will be the set fps value.

**Comment by NotStanley4330** [comment]
Alright so I see that the issue is that we don't seem to actually pull in the info to the settings menu initially. I wonder why we do it this way:

```
const int realframes = 1000 / gwin->get_std_delay();

frames                        = -1;
framerates[num_default_rates] = realframes;
for (size_t i = 0; i < num_default_rates; i++) {
if (realframes == framerates[i]) {
	frames = i;
	break;
}
}

size_t num_framerates = num_default_rates;
if (frames == -1) {
num_framerates++;
frames = num_default_rates;
}
frametext.clear();
for (size_t i = 0; i < num_framerates; i++) {
frametext.emplace_back(framestring(framerates[i]));
}
```
So it creates this dynamically on startup and doesn't load in the frame values until you start a game, but do we have a distinct need for these things to be created dynamically? I can work within it however. Just seems odd.

**Comment by DominusExult** [comment]
That's odd. It should just read it in the setting from the xml. But might be that historically it had some reason two decades ago :)

**Comment by NotStanley4330** [comment]
> That's odd. It should just read it in the setting from the xml. But might be that historically it had some reason two decades ago :)

I agree. I can see that it's creating a list of text options but it just never actually loads from the xml. Should be like a 2 line fix

**Comment by NotStanley4330** [comment]
Got a PR submitted for this one!

**Comment by NotStanley4330** [comment]
New PR submitted that should fix this and rework the backend slightly to be less convoluted
