### ISSUE TITLE
Mouse warp - do we need this anymore?

### ISSUE THREAD

**Issue by DominusExult** [exult/exult#544]
Especially @wench since you wrote that 14 years ago in mouse.cc and @Dragon-Baroque since it also concerns SDL3 just a bit.

See https://github.com/libsdl-org/SDL/issues/10413 <- there is an issue with global  mouse warp emulation (it's an SDL3 issue not really ours).
But commenting these SDL_WarpMouseInWindow() in our two occurrences makes no visible difference to me on macOS. So I wonder if we actually still need this anymore.
https://github.com/exult/exult/blob/master/mouse.cc#L162 (added 14 years ago)
https://github.com/exult/exult/blob/master/gamewin.cc#L1969 (added 23 years ago)

**Comment by wench** [comment]
Can't remember why I added it but I am thinking it was to reduce annoyances
when the mouse cursor leaves the exult window when doing right drags to
move. should guard the code so it only gets called if the mouse is outside
of the Exult window. if the mouse is already in the Exult window it should
not be called, and never for touch.

**Comment by wench** [comment]
The call in mouse.cc seems like it keeps the system mouse in a specific region when fast mouse is enabled and only when fast mouse is enabled. It's not for right dragging as I thought. It shouldn't affect touch. After a quick test I can tell what it's doing If fast mouse is enabled the mouse cursor sort of gets stuck on the right and bottom edges of the screen. Its not actually stuck but the mouse cursor is actually far beyond the edge of the game screen so it needs a lot of motion to come back on screen but the cursor in Exult is drawn as if it is at the edge of the screen. What this code does is if the mouse cursor moves beyond the edge of thegame screen when fast mouse is enabled it moves the system mouse to where it appears to be in Exult. If mouse warping will be a problem I could remove this and replace it with a different fix

The one is gamewin.cc I have no idea about, I didn't make this change. It is only called after a teleport is done and I do not know what problem it is trying to fix. The comment above says it is for `generate mousemotion event` no idea why that would need to happen, but I'm pretty sure it is wrong and shouldn't be done. I would remove it because it doesn't seem to do anything useful and is causing trouble for touch. The problem it is trying to fix may have already have been fixed elsewhere

**Comment by wench** [comment]
Actually Just testing and Forcing mouse appearance to update seems to be exactly what it does. After using the map to teleport, the mouse cursor will be wrong and show the direction and size it was before  showing the map. A quick test shows this is a more general problem affecting anything that that stops the main event loop from updatinngthe mouse cursor.
For example. Move the mouse to the top left corner of the screen. Press escape to show the ingame menu. Press the checkmark to close the gump. The mouse cursor will be the wrong arrow for where it is on screen. This Warp call fixes this after using the map teleport cheat, but nothing else. I'll make a more general fix for this issue.

**Comment by wench** [comment]
I pushed a change for the mouse cursor problem and removed the call to SDL_WarpMouseInWindow in gamewin.cc

**Comment by DominusExult** [comment]
thank you very much for looking into this!

**Comment by Dragon-Baroque** [comment]
Wench, the issue that caused Dominus to ask you to review the use of MouseWarp in Exult was :
- A cursor freeze I had just after a transition Windowed -> Fullscreen or back, in the port of Exult to SDL 3, under Wayland.
- The freeze was quickly bypassed in hinting SDL 3 as __Not to use the Mouse Warp emulation based on the Mouse Relative Mode__ - that looks like a confinement of the Mouse provided by the compositor, Wayland here.
- Later the SDL 3 team found the culprit code and made the transitions Windowed <-> Fullscreen working again, even using the Mouse Warp emulation,
- Finally the SDL 3 team expanded the Mouse Warp emulation to encompass Quartz ( macOS ), and the cursor mismanagement showed up again.

Dominus, am I fair ?

**Comment by DominusExult** [comment]
Yeah, but mostly because I couldn’t see any differences in both implementations (and I still don‘t for fastmouse+fullscreen+macOS 🤷‍♂️ - still takes me around the same time scrolling until the mouse cursor does anything on the screen).

**Comment by wench** [comment]
I'll remove the remaining mouse warp from mouse.cc I don't have a good reason not to and as I know what the problem it is trying to solve is, I can implement a better fix in Exult's mouse code that will work properly for everyone and not rely on a feature in SDL that may not work properly for everyone.

**Comment by wench** [comment]
Ok I removed the final call to `SDL_WarpMouseInWindow`  and changed how the fix for fast mouse cursor getting stick on right and bottom edges works. 
I have a slight concern that fast mouse and HiDPI may not play nice together and I would appreciate if it can be tested. HiDPI input is only used in  couple places so if they could all be tested it would be nice. I an unable to test these as high DPI doesn't work on Windows. The situations that need testing with HiDPI and fast mouse are Teleport to Cursor Cheat, Delete Object Under Cursor Cheat, Right Dragging to move the player and during Wizard Eye. When testing it would be important to first push the mouse out of the bottom or right edge of the screen. 

One unexpected thing I noticed making this change. Previous with Fast Mouse and warping it wasn't possible to move the mouse out of the Exult Screen to a monitor to the right in a Multi monitor setup. With this change it is now possible but as you can't see where the system mouse cursor it, it may take a lot of movement at high scaling factors for the mouse to actually leave the Exult screen and you can't tell as the mouse cursor will appear on the right edge of the screen in Exult but the system cursor may be nowhere near the right edge of the monitor

**Comment by DominusExult** [comment]
Aside from the compile problems (for both commits I need to extend the imagewin/makefile.am to include certain folders but the last commit needs` include gamewin.h` in mouse.h or it fails where Game_window is called), this implementation is much better in regards to initial change to fullscreen.
I'll test Highdpi now.

**Comment by wench** [comment]
I'm trying to fix the header problems now. I had no idea the build systems didn't include all the directories in the include path causing errors when including mouse.h

**Comment by DominusExult** [comment]
with your last commit you have caused more problems:
- Including with the path (`#include "shapes/vgafile.h"`) causes problems with Xcode and possibly other build systems. You need to change the makefile.am file and inlcude the folders in `AM_CPPFLAGS =` line.
- mouse.h needs gamewin.h

So the fix is inluding gamewin.h again in mouse.h and change imagewin/Makefile.am by adding -I$(top_srcdir)/shapes -I$(top_srcdir)/objs to the top line

**Comment by wench** [comment]
Looks like all the compile problem are now fixed

**Comment by wench** [comment]
The CI build are now passing for Macos and Linux. If there is a specific problem with XCode, you'd need to fix it as the ci-macos workflow sucessfully builds so I can't tell what impact it would actually have.

**Comment by DominusExult** [comment]
May I revert these partially to use the AM_CPPFLAGS way that was set up previously?

Highdpi is not working, the coordinates are not aligned but now I remember that this never worked before - I guess it would need to use nativescale as in `void Image_window::screen_to_game_hdpi`

**Comment by wench** [comment]
The build systems need fixing though as including gamewin.h should never cause an error. It is just an integral part of Exult, It should work when included from any source file. Removing gamewin from mouse.h caused moreproblems than expected as it seems that a few files were getting their include of gamewin through mouse.h

**Comment by wench** [comment]
Make any changes you see fit. All workflows pass for my last commit so I don't want to change things myself.

Does HiDPI work properly without fast mouse? Looking at `screen_to_game_hdpi` I'm not convinced it works as expected. It applies the `nativescale` factor to the output game screen coords but I would have thought it make more sense to apply the factor to the input screen space coords that have come from SDL. To me I would think that the normal screen_to_game should apply the hidpi factor and there should be no need for a separate one. I wonder if there is someway I could hack things to simulate HiDPI without actually having it

**Comment by DominusExult** [comment]
Hmm, it used to work with fastmouse disabled. I *now* find that teleport to cursor and delete object from cursor do indeed no longer work.
Mouse walk and Wizard's eye do work, though.

**Comment by wench** [comment]
I'll fix the HiDPI stuff but not today. I have a pretty good idea how to simulate it

**Comment by wench** [comment]
I have implemented simulating HIghDPI locally and the issues are exactly what I expected. Will fix shortly

**Comment by DominusExult** [comment]
How did you simulate it? No need to go into details, just the general ghist as this sounds interest. Mucking with SDL sources and/or external tools?
And last time I looked (quite some time ago) into Windows and HighDPi, the software side requirements were not clear (entries in Exult’s manifest.xml?), can you tell me what is needed?

**Comment by wench** [comment]
No I just changed things so Exult always calls SDL_RenderSetLogicalSize with a higher resolution than the actual screen resolution.

I pushed changes that fix fast mouse and HIGHDPI.

**Comment by DominusExult** [comment]
thank you, works great now.

Got this warning though:
```
imagewin.cc:645:41: warning: operator '?:' has lower precedence than '|'; '|' will be evaluated first [-Wbitwise-conditional-parentheses]
        uint32 flags = SDL_SWSURFACE | highdpi ? SDL_WINDOW_ALLOW_HIGHDPI : 0;
                       ~~~~~~~~~~~~~~~~~~~~~~~ ^
imagewin.cc:645:41: note: place parentheses around the '|' expression to silence this warning
        uint32 flags = SDL_SWSURFACE | highdpi ? SDL_WINDOW_ALLOW_HIGHDPI : 0;
```

Need to see how this translates to the SDL3 fork (as that generally worked better without having to mess with extra HighDPi.

**Comment by wench** [comment]
Fixed the warning

**Comment by wench** [comment]
Closing this

**Comment by DominusExult** [comment]
Sorry, I have to reopen.
When you have a HighDPi monitor but in Exult HighDPi disabled and Fastmouse disabled you can only access the normal DPi part of the screen (in my case 3200x1800). If you use a higher resolution you are still restircted to the rectangular of 3200x1800 which starts in the upper left corner.
Other combinations work (HighDPi enabled&Fastmouse disabled, HighDPi disabled&Fastmouse enabled).

**Comment by wench** [comment]
id suggest undoing my change to to line 645 of inagewin.cc and reverting  `highdpi ? SDL_WINDOW_ALLOW_HIGHDPI : 0` back to just `SDL_WINDOW_ALLOW_HIGHDPI ` and seeing if that helps, otherwise I have no idea

**Comment by wench** [comment]
Line 672 might also be a problem try removing `&& highdpi` from that line. If those fix things feel free to commit the changes

**Comment by DominusExult** [comment]
it was line 672. Thank you, I'll commit (I tried all these combinations again, I don't think I missed something now)

**Comment by Dragon-Baroque** [comment]
> Need to see how this translates to the SDL3 fork (as that generally worked better without having to mess with extra HighDPi.

I have rebased and force pushed my branch `exult-sdl3` onto the latest master commit 9d1a2fce0.
I am not sure of myself in `imagewin/imagewin.cc` in the `if (fullscreen) {` code branch lines 695..723.
- The `#ifdef SIMULATE_HIDPI` and `#ifdef SDL_PLATFORM_IOS` seem to collide,
- The `nativescale` variable does not exist in the SDL 3 code, I may have removed it some time ago because in SDL 2 it is set - by that code section actually - **but never used**.

**Comment by wench** [comment]
Nativescale isn't used in master anymore either because I removed the code that used it and fixed the underlying problem that needed it. I left the field in imagewin just in case it was wanted for something else in the future
