### ISSUE TITLE
Cheat screen for android

### ISSUE THREAD

**Issue by i30817** [exult/exult#607]
Obviously, you can't use keyboard shortcuts in the android version of exult, not in the least because the onscreen keyboard can't be enabled but also because the native android onscreen keyboard doesn't have any notion of Ctrl. 

So a menu based alternative would be nice.

**Comment by DominusExult** [comment]
The cheat screen works on the Android version (enable cheats and double tap on the notebook in the shortcuts bar).

1. there is really something wrong with the keyboard on my older real device when used with the cheat screen. The keyboard is supposed to pop up when you enter the cheat screen. Which it does but then hide on a tap outside of the keyboard, which it also does. But it only pops up for a second when you touch the screen again. That is wrong ;(
But...
2. Alexis implemented that you can tap the cheat screen items and if you have to enter a number you can slide your finger over the screen to get to the real number.

**Comment by i30817** [comment]
Btw since the other exult u6 mod bug report I opened got closed, I'm hesitant to open another, but I did notice that exult appears to get into a softlock when having 6 followers + avatar (u6 is supposed to allow 8 party members total, might fatally crash the pathfinding).

I can still hear sounds but can't click the shortcut icons or move. If I minimize and pull it up, I get a black screen except for the controller overlay (esc and the joystick\pad in android).

**Comment by DominusExult** [comment]
I really don't want to be that guy, but please stay on topic. This one is about Android cheat screen and your issue is not related to the cheat screen and maybe not even related to Android.

And in the case of mods, really contact the creator first. It could very well be an Exult bug but this needs to be determined before we look into it.
And then the bug report needs to be more elaborate (logs, usecode bing used etc.)
