### ISSUE TITLE
nightly build notification spam

### ISSUE THREAD

**Issue by rofl0r** [exult/exult#84]
i'm getting notified everyday about a nightly build. imo those builds should only be made if there was a change. also they create a release - probably it would be better to just manually create a release tag now and then.

**Comment by marzojr** [comment]
I was testing the feature and fixing bugs with it, which is why there was the recent notification spam. It does only generate a new build if there have been commits in the previous 24 hours. I will also be investigating a way to not send messages when the generation succeeds.

But now you wasted my time in having to triage this non-issue and write up this reply, good going.

**Comment by mfn** [comment]
Came here to say the same thing.

I was specifically watching this repo only for releases to be, well, notified about new releases.

It's awesome that there's activity going on, but this makes this github ability rather moot as a snapshot release has less significance for non-developers … 😢 

Github doesn't allow fine tune this (like: only be notified of non-`pre` releases), but it wouldn't matter as the snapshots are created as final release. But I'll contact github for this feature request anyway :)
